### ISSUE TITLE
bug: <简中字幕无法生成>

### ISSUE THREAD

**Issue by QAQ2077** [zjns/BiliRoamingX-integrations#1]
### Type

Cosmetic

### Bug description

简中字幕跟没用一样，我也不知道咋搞
照片不知道怎么上传不上去了

### Steps to reproduce

1.生成简中字幕
2.然后就无法使用

### Relevant log output

```shell
无
```

**Comment by QAQ2077** [comment]
用了跟繁体一模一样，不知道是不是我的问题

**Comment by zjns** [comment]
> 用了跟繁体一模一样，不知道是不是我的问题

卸载重装APP试试

**Comment by zjns** [comment]
还有要自己手动在字幕列表里面选生成的。

**Comment by QAQ2077** [comment]
#

**Comment by QAQ2077** [comment]
没用啊，卸载也重装过，也不知道咋回事

**Comment by QAQ2077** [comment]
https://wwgt.lanzoum.com/iFkZx119bhpa

**Comment by zjns** [comment]
https://github.com/zjns/BiliRoamingX-integrations/releases/download/20230705-debug/Bili-v7.36.0-b12290539-patched.apk 用这个包试试，把日志发出来。

**Comment by QAQ2077** [comment]
好像有点用,日志看看怎么发？

**Comment by zjns** [comment]
> 好像有点用,日志看看怎么发？

啥都没改，打开调试模式，用mt文件管理器把log.txt拿出来。

**Comment by QAQ2077** [comment]
好吧，经过测试应该没有用，之前测试我好像用了lsp模块，我之前好像取消，不知道为啥就勾选上了，用模块就没啥问题，用这个的话，这里也没啥用，难道也要重装一下才行吗？
https://wwgt.lanzoum.com/iTWF911l9wza
我再试试

**Comment by zjns** [comment]
试一下开启 “其他播放设置” 里的 “启用
https播放”。

**Comment by zjns** [comment]
你是开了免流吗？应该是免流的问题，抽空处理下。

**Comment by zjns** [comment]
https://github.com/zjns/BiliRoamingX-integrations/releases/download/20230707-debug/Bili-v7.36.0-b12290539-patched.apk 试下这个包，应该没问题了。
