### ISSUE TITLE
bug: 7.41.0版本系列问题

### ISSUE THREAD

**Issue by GreenDreenAct** [zjns/BiliRoamingX-integrations#10]
### 系统版本

Oneui 5.1

### Android 版本

13

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.41.0

### 问题描述

哔哩漫游失效，开屏推广去不掉

### 复现步骤

港澳台番剧点开

### 日志

[log.txt](https://github.com/zjns/BiliRoamingX-integrations/files/12239504/log.txt)

### 截图或录屏

`
![Screenshot_20230802_192126](https://github.com/zjns/BiliRoamingX-integrations/assets/141235179/62e8a890-4a1b-4b77-ae5c-994e603c5f9f)

**Comment by zjns** [comment]
灰度到了新版播放器及视频详情页，改动很多，抽空适配。
