### ISSUE TITLE
feat: 无限试用画质的另一种方法？

### ISSUE THREAD

**Issue by snowEdayz** [zjns/BiliRoamingX-integrations#101]
### 原因

无限试用画质的另一种方法？

### 功能简述

伪装大会员无限试用画质

### 功能逻辑

hook

### 实现参考

让 `Lcom/bilibili/lib/accountinfo/BiliAccountInfo;->isEffectiveVip()Z` 返回 `true`。测试7.66.0版本仍有效。需设置为旧版播放器，新版播放器不生效。同时这可以离线缓存并播放大会员视频。

**Comment by zjns** [comment]
伪装大会员跟现在的处理方式效果是一样的，而且伪装大会员会影响很多地方，个人是不喜欢这种方式。只能看不能下载是故意这样设计的，毕竟你不是会员，下载就涉及侵权了。
