### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by han5211506** [zjns/BiliRoamingX-integrations#102]
### 系统版本

澎湃OS

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.66.0

### 问题描述

评论区显示错误
![Screenshot_2024-02-07-10-33-34-901_tv danmaku bili](https://github.com/zjns/BiliRoamingX-integrations/assets/65791439/03025d6e-6f57-490e-ae00-d4378a013b61)

### 复现步骤

评论区显示错误

### 日志

[de50b5fda8564f53d171ec842ce9c492.txt](https://github.com/zjns/BiliRoamingX-integrations/files/14188561/de50b5fda8564f53d171ec842ce9c492.txt)

### 截图或录屏

![Screenshot_2024-02-07-10-33-34-901_tv danmaku bili](https://github.com/zjns/BiliRoamingX-integrations/assets/65791439/72cfbd12-062f-48fb-834c-ab92fddaef4a)

**Comment by zjns** [comment]
系统问题
