### ISSUE TITLE
部分功能失效

### ISSUE THREAD

**Issue by yajie6** [zjns/BiliRoamingX-integrations#103]
### 系统版本

Hyper os1.0.5.0

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.66.0

### 问题描述

自动刷新功能屏蔽失败，每次开启软件都刷新。
解锁画质失败，旧版也不行，怀疑软件启动页屏蔽功能也失效了
![Screenshot_2024-02-11-17-29-41-631_tv danmaku bili](https://github.com/zjns/BiliRoamingX-integrations/assets/133912773/67b22792-5dfc-4332-a80a-68570df6e098)

### 复现步骤

打开任何视频或者重新进入

### 日志

[log.txt](https://github.com/zjns/BiliRoamingX-integrations/files/14233163/log.txt)
[old_log.txt](https://github.com/zjns/BiliRoamingX-integrations/files/14233164/old_log.txt)

### 截图或录屏

![Screenshot_2024-02-11-17-38-31-316_tv danmaku bili](https://github.com/zjns/BiliRoamingX-integrations/assets/133912773/743332c8-c5d7-4cf0-8d49-054811ce454f)
![Screenshot_2024-02-11-17-38-25-642_tv danmaku bili](https://github.com/zjns/BiliRoamingX-integrations/assets/133912773/d0b5348c-f36c-4630-b60d-47c2a1d8e689)
![Screenshot_2024-02-11-17-38-22-101_tv danmaku bili](https://github.com/zjns/BiliRoamingX-integrations/assets/133912773/fa5d4204-8f44-4ede-a5d2-52fa9cfbb1b3)
![Screenshot_2024-02-11-17-29-41-631_tv danmaku bili](https://github.com/zjns/BiliRoamingX-integrations/assets/133912773/0681b84a-9fa6-4d1f-a565-815629d165da)

### 补充信息

所有

**Comment by yajie6** [comment]
我的说法有问题，是最新版开屏页面屏蔽失败了

**Comment by zjns** [comment]
无法复现

**Comment by yajie6** [comment]
您好，我这个log里没有任何异常吗，不应该啊，自动刷新屏蔽我在多设备测试，都失效了，每次开启app都会自动刷新



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年02月12日 05:11 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [zjns/BiliRoamingX-integrations] 部分功能失效 (Issue #103) |

Closed #103 as not planned.

**Comment by yajie6** [comment]
这玩意是真不起作用啊 您能不能再测试一遍，每次重新打开都自动刷新 我已经重启超过20遍了，谢谢您



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年02月12日 05:11 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [zjns/BiliRoamingX-integrations] 部分功能失效 (Issue #103) |

Closed #103 as not planned.

**Comment by zjns** [comment]
> 这玩意是真不起作用啊 您能不能再测试一遍，每次重新打开都自动刷新 我已经重启超过20遍了，谢谢您

你把APP杀了之后冷启动首页内容当然会刷新！

**Comment by yajie6** [comment]
哦哦哦哦，打扰了哈哈哈



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年02月13日 02:33 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [zjns/BiliRoamingX-integrations] 部分功能失效 (Issue #103) |

这玩意是真不起作用啊 您能不能再测试一遍，每次重新打开都自动刷新 我已经重启超过20遍了，谢谢您

你把APP杀了之后冷启动首页内容当然会刷新！
