### ISSUE TITLE
feat: 可以设置默认显示用户uid 

### ISSUE THREAD

**Issue by mopiao124** [zjns/BiliRoamingX-integrations#106]
### 原因

我的关注人数上限了，不知道再如何标记我想标记的用户，目前采用截屏存图。但不点开简介只能截到昵称（就算截到了用户的投稿可以去搜标题，但也怕ta删稿或存在标题重复），用户修改后就搜不到了，但其uid不会改变，更保险和方便。每次需手动点开简介太麻烦且易忘，希望能增加自动显示用户uid的设置。

### 功能简述

不用点开简介，用户页面就展示uid，比如可以显示在ip地址旁边

### 功能逻辑

添加设置选项

**Comment by zjns** [comment]
无聊的需求自己想办法
