### ISSUE TITLE
bug：播放视频时突然黑屏退出，且无播放记录

### ISSUE THREAD

**Issue by zzqsld** [zjns/BiliRoamingX-integrations#110]
### 系统版本

coloros14

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.67.0

### 问题描述

在播放视频时突然黑屏，软件自动返回上一个界面，相关内容重新加载之后，在播放记录中无法找到刚才播放的视频

### 复现步骤

该黑屏bug出现时机随机，本人在开启调试模式之后复现该问题

### 日志

[log.zip](https://github.com/zjns/BiliRoamingX-integrations/files/14580530/log.zip)
此压缩包包含log文件和logold文件

### 截图或录屏

已提供日志

**Comment by zjns** [comment]
日志文件下载失败，重新传下呢

**Comment by zjns** [comment]
这个之前好像排查过，native层的报错，感觉是b站官方的bug

**Comment by zjns** [comment]
等官方修复吧
