### ISSUE TITLE
feat: 请求添加调整我的页个性主题头图显示区域功能

### ISSUE THREAD

**Issue by bheith** [zjns/BiliRoamingX-integrations#111]
### 原因

购买的装扮实际头图显示区域比官方预览区域小太多
![Screenshot_20240317-041644](https://github.com/zjns/BiliRoamingX-integrations/assets/99644063/fde3a3e7-91ba-4933-b687-4f2c595ae87c)
![qq_pic_merged_1710620505222](https://github.com/zjns/BiliRoamingX-integrations/assets/99644063/6057ed3a-d079-4bb2-a78f-10094f62db64)

### 功能简述

想要扩大显示区域的功能，这样就能看到更多部分的动态头图了。

### 功能逻辑

按画幅比例或自定义区域像素大小的方式调整

**Comment by bheith** [comment]
如果能展示个性主题头图整个画幅就更好了，或许还能添加我的页项目半透明显示在头图上的功能

**Comment by zjns** [comment]
别移除我的大会员横幅就行了

**Comment by bheith** [comment]
> 别移除我的大会员横幅就行了

移除横幅确实好了，不过现在大会员横幅不是透明的，还是会遮挡部分区域，可惜
