### ISSUE TITLE
bug: 粉版离线缓存视频无法打开

### ISSUE THREAD

**Issue by ogog45** [zjns/BiliRoamingX-integrations#112]
### 系统版本

magic os 8

### Android 版本

13

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.70

### 问题描述

离线视频打开后页面app全黑无法加载出任何东西智能返回

### 复现步骤

rt

### 日志

rt

### 截图或录屏

![Screenshot_20240317_093042_tv danmaku bili](https://github.com/zjns/BiliRoamingX-integrations/assets/61620298/bf30ead3-bbd2-4961-b892-bd92577458d2)

**Comment by zjns** [comment]
日志呢？无法复现

**Comment by zjns** [comment]
还有操作步骤，哪个视频的缓存，什么画质

**Comment by ogog45** [comment]
旧版升级安装的，刚才卸载再装ok了

**Comment by zjns** [comment]
> 旧版升级安装的，刚才卸载再装ok了

开启旧版播放器就会有这个问题，已经发了个补丁包修复了。
