### ISSUE TITLE
视频下方推荐过滤-仅up主投稿视频不生效

### ISSUE THREAD

**Issue by resupinel** [zjns/BiliRoamingX-integrations#113]
### 系统版本

miui12.5

### Android 版本

11

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.70.0(上个版本好像也没生效）

### 问题描述

打开移除推广和仅up主投稿视频后，视频下方仍会推荐其他up主视频

### 复现步骤

打开仅up主投稿视频并重启软件，该功能不生效

### 日志

无

### 截图或录屏

![Screenshot_2024-03-17-10-11-41-638_tv danmaku bili](https://github.com/zjns/BiliRoamingX-integrations/assets/78926791/05d43283-9cef-416f-8af4-41cd694295dd)
![Screenshot_2024-03-17-10-10-26-677_tv danmaku bili](https://github.com/zjns/BiliRoamingX-integrations/assets/78926791/3c048852-e4ad-405a-85fd-e59d9a34e389)

**Comment by zjns** [comment]
仅up主投稿视频不是特指当前up主的视频，而是说这些推荐有可能包含番剧、电影等内容，将这些内容移除。
