### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by 114511e** [zjns/BiliRoamingX-integrations#114]
### 系统版本

鸿蒙4.0.0.200

### Android 版本

鸿蒙4.0.0.200

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.70.0

### 问题描述

允许检查预构建包更新功能故障，打开b站的时候检测出了个7.70.1的，然后下载了一半多说下载失败，然后重新开了几次b站都没跳出来过这个更新

### 复现步骤

无法跳出更新

### 日志

[log.txt](https://github.com/zjns/BiliRoamingX-integrations/files/14626618/log.txt)

**Comment by zjns** [comment]
网络问题，在关于哔哩哔哩设置里可以点击检查更新按钮手动更新。
