### ISSUE TITLE
feat: 视频画面尺寸选项记住

### ISSUE THREAD

**Issue by iTeraxo** [zjns/BiliRoamingX-integrations#115]
### 原因

![IMG_20240321_010520](https://github.com/zjns/BiliRoamingX-integrations/assets/104311389/daed8405-c3e1-473d-8172-c91c36fb50b0)
调整画面尺寸后，下一个视频会恢复为适应尺寸，很不方便

### 功能简述

将画面尺寸调整后，能够记住该选项；或者能够将默认画面尺寸修改为除适应外的其他选项

### 功能逻辑

添加"画面尺寸选项保持"开关

**Comment by zjns** [comment]
添加了双指缩放切换画面尺寸
