### ISSUE TITLE
bug: 净化分享链接导致应用卡死

### ISSUE THREAD

**Issue by 3049298988** [zjns/BiliRoamingX-integrations#116]
### 系统版本

MIUI14.0.23.8.21.DEV

### Android 版本

13

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.70.0（包括Play版，HD版本未尝试）

### 问题描述

净化分享链接导致应用卡死

### 复现步骤

打开净化分享链接功能
选择视频分享
卡死
（分享到其他应用/剪贴板）

### 日志

[Play版.txt](https://github.com/zjns/BiliRoamingX-integrations/files/14671109/Play.txt)
[普通版.txt](https://github.com/zjns/BiliRoamingX-integrations/files/14671110/default.txt)

**Comment by zjns** [comment]
无法复现，哪个视频，关闭调试模式试试，日志上传old.txt也上传上来

**Comment by 3049298988** [comment]
任意视频（竖屏/横屏）
全新安装，所以没有old.txt

**Comment by 3049298988** [comment]
[普通.zip](https://github.com/zjns/BiliRoamingX-integrations/files/14681397/default.zip)
[Play.zip](https://github.com/zjns/BiliRoamingX-integrations/files/14681406/Play.zip)

**Comment by zjns** [comment]
不用流量，用WiFi试试

**Comment by 3049298988** [comment]
好像正常了。。。
你一说我觉得应该是代理问题
我那个全局代理的赛博美国人朋友也会卡10多秒

**Comment by 3049298988** [comment]
>~~使用 [BiliBili](https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.yaml)规则集即可解决这个问题~~

是
```yaml
auto-route: true
```
的问题
但是不开这玩意会泄漏到你奶奶都不认识（）
所以还是把哔哩哔哩设置到排除包名了
```yaml
exclude-package: ["tv.danmaku.bili"]
```
