### ISSUE TITLE
feat: 在播放器底部显示常驻进度条

### ISSUE THREAD

**Issue by 455ass** [zjns/BiliRoamingX-integrations#118]
### 原因

tv上的第三方客户端都有这个功能，并且非常好用，视频播放到哪了看一眼就行

### 功能简述

就在播放器底部显示一个常驻进度条，大小可以自定义，颜色跟随主题

### 功能逻辑

在播放器的其他控件都隐藏后，在视频最下方显示一个常驻进度条

### 实现参考

类似于这样
![Screenshot_20240321_184426](https://github.com/zjns/BiliRoamingX-integrations/assets/91419962/8b5f7f75-7abe-4e5d-8dca-59f5318113dc)
![Screenshot_20240321_184743](https://github.com/zjns/BiliRoamingX-integrations/assets/91419962/e5c2d690-1f37-4021-924a-9fbf68e82d8e)

**Comment by zjns** [comment]
HD版本会显示进度条，粉版曾经某个内侧版本把进度条弄出来了，被当成bug处理了
