### ISSUE TITLE
直播间右侧和下侧显示不正常

### ISSUE THREAD

**Issue by Sooonar** [zjns/BiliRoamingX-integrations#119]
### 系统版本

originos4

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.70.0

### 问题描述

在打开直播间时，先显示正常，然后就马上闪一下。就会有下图的黑边了。
直播间右侧和下侧有黑边。

### 复现步骤

竖屏直播间会一直出现，横屏直播间偶尔会触发。

### 日志

大佬，不好意思。不太会上传日志。

### 截图或录屏

![Screenshot_20240323_164058](https://github.com/zjns/BiliRoamingX-integrations/assets/124046604/6f11871c-d0ba-45d1-a59b-9e515e0022ca)

**Comment by zjns** [comment]
确实有问题，临时解决办法是将杂项显示大小先调回默认。
