### ISSUE TITLE
bug: play深色splashscreen图标有白框

### ISSUE THREAD

**Issue by Lingodbeast** [zjns/BiliRoamingX-integrations#120]
### 系统版本

harmony 4

### Android 版本

12

### 哔哩哔哩版本

Play 版（国际版）

### 哔哩哔哩版本号

3.18.2

### 问题描述

 :play深色splashscreen图标有白框

### 复现步骤

 :play深色splashscreen图标有白框

### 日志

[log.txt](https://github.com/zjns/BiliRoamingX-integrations/files/14734208/log.txt)

**Comment by Lingodbeast** [comment]
![Videoframe_20240324_103502_com huawei himovie local](https://github.com/zjns/BiliRoamingX-integrations/assets/77826305/9dffde13-9c2b-4dff-837e-d39f1ace99c9)

**Comment by Lingodbeast** [comment]
![Videoframe_20240324_103502_com huawei himovie local](https://github.com/zjns/BiliRoamingX-integrations/assets/77826305/0328bc07-8ec7-4988-93a1-94010a7d4c32)

**Comment by zjns** [comment]
鸿蒙系统问题

**Comment by Lingodbeast** [comment]
能否增加开关关闭 splashscreen，谢谢

**Comment by zjns** [comment]
不能

**Comment by Shinosuke5** [comment]
好像自定义整个界面的不会有显示问题

https://github.com/zjns/BiliRoamingX-integrations/assets/77826305/abf633d1-4a36-430e-9456-9908e5a23bf8
