### ISSUE TITLE
屏蔽评论

### ISSUE THREAD

**Issue by John1999z** [zjns/BiliRoamingX-integrations#121]
### 原因

搜索的时候。
![Screenshot_2024_0324_131304](https://github.com/zjns/BiliRoamingX-integrations/assets/154442352/78e5de0b-f404-4391-9844-c3e80e9d5f5f)
会有如下图片显示的精彩评论

### 功能简述

我想要把这个功能屏蔽

### 功能逻辑

就是做出一个漫游里面的开关

**Comment by zjns** [comment]
无聊
