### ISSUE TITLE
评论的屏蔽项

### ISSUE THREAD

**Issue by John1999z** [zjns/BiliRoamingX-integrations#122]
### 原因

![20_46_43_316284923-78e5de0b-f404-4391-9844-c3e80e9d5f5f](https://github.com/zjns/BiliRoamingX-integrations/assets/154442352/174426cc-1474-488c-8660-8e5e36d5ee49)

### 功能简述

搜索到的视频下面的精彩评论显示。你做出一个给他屏蔽的开关吧。

### 功能逻辑

仅此而已

**Comment by zjns** [comment]
要我重复几遍，无聊，自己想办法弄。
