### ISSUE TITLE
bug: 解除播放限制后，后台播放功能不能关闭

### ISSUE THREAD

**Issue by a6886126** [zjns/BiliRoamingX-integrations#123]
### 系统版本

MIUI14

### Android 版本

13

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.70.0

### 问题描述

打开 “解除部分版权视频禁止后台播放、小窗播放、投屏、听视频等限制” 后 ，在版权视频下，后台播放功能标识始终是开的，不能开关

要在版权视频里才能复现，比如up主索尼音乐中国的【官方 MV】Never Gonna Give You Up - Rick Astley  

bv号：BV1GJ411x7h7

### 日志

[Uploading log.txt…]()

**Comment by do02fw** [comment]
希望更新7.72

**Comment by do02fw** [comment]
希望更新7.72版本
