### ISSUE TITLE
想要首页视频封面4:3，不习惯16:9   

### ISSUE THREAD

**Issue by xiannvranran** [zjns/BiliRoamingX-integrations#124]
### 原因

感觉首页4:3的视频封面比较舒服

### 功能简述

首页视频封面能切换4:3和16:9

### 功能逻辑

能自由切换4:3和16:9的视频封面

### 实现参考

哔哩漫游能切换，但是x没有
![Screenshot_2024-03-29-16-01-06-768_tv danmaku bili](https://github.com/zjns/BiliRoamingX-integrations/assets/165369200/5fb26092-1bdd-4fb9-9f12-3cb61f6dbfe4)

**Comment by xiannvranran** [comment]
希望能采纳这个小小的建议

**Comment by zjns** [comment]
没卵用，接口返回的封面只有4:3比例的，16:9是裁切实现的。

**Comment by kljjh** [comment]
> 没卵用，接口返回的封面只有4:3比例的，16:9是裁切实现的。

16:9比4:3一页能多显示几个视频 用习惯了16:9切回4:3还挺难适应的
