### ISSUE TITLE
如何使用Revanced?

### ISSUE THREAD

**Issue by HSSkyBoy** [zjns/BiliRoamingX-integrations#125]
### 原因

单纯询问

### 功能简述

我们是必须等您的集合包，还是可以自己用Revanced打包？如果可以的话，该怎么做？

### 功能逻辑

使用Revanced自己打包

**Comment by pasical** [comment]
> 请问解决了吗？如何解决的？

已解决

**Comment by zjns** [comment]
> > 请问解决了吗？如何解决的？
> 
> 已解决

https://github.com/BiliRoamingX/BiliRoamingX?tab=readme-ov-file#%EF%B8%8F-%E4%B8%8B%E8%BD%BD%E4%BD%BF%E7%94%A8
