### ISSUE TITLE
虽然大佬随缘更新了，但希望能集成哔哩发评反诈模块

### ISSUE THREAD

**Issue by Morris-Lucifer** [zjns/BiliRoamingX-integrations#128]
### 原因

不知道应该在哔哩漫游那还是在这里提这个issue，总之这个[模块](https://github.com/freedom-introvert/biliSendCommAntifraud)应该算b站用户痛点了，可惜手机不能root :(

### 功能简述

这个模块可以检测评论是否真发送成功

### 功能逻辑

需要登录cookie，详情见模块仓库

**Comment by zjns** [comment]
麻烦，不值得浪费时间
