### ISSUE TITLE
动态视频显示bug

### ISSUE THREAD

**Issue by Maybeyok** [zjns/BiliRoamingX-integrations#129]
### 系统版本

HyperOS 1.0.6.0

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.70.0

### 问题描述

打开动态，有时显示的不是最新视频，会显示up主以前投稿的视频，每次只是显示一个这种视频，其他的视频正常。

### 复现步骤

打开动态，显示up主以前投稿的视频

### 日志

[log.txt](https://github.com/zjns/BiliRoamingX-integrations/files/14830858/log.txt)

**Comment by Maybeyok** [comment]
![Screenshot_2024-04-02-11-26-42-297_tv.danmaku.bili.jpg](https://github.com/zjns/BiliRoamingX-integrations/assets/127712226/84ba8dbe-8d9d-4616-8473-dc45a2b9fe7c)

![Screenshot_2024-04-02-11-26-46-870_tv.danmaku.bili-edit.jpg](https://github.com/zjns/BiliRoamingX-integrations/assets/127712226/cb95967e-3332-4366-bc08-3ee1f479e458)

**Comment by zjns** [comment]
这不是模块的问题吧，可能是官方故意这样弄的。
