### ISSUE TITLE
bug: 加载视频闪退

### ISSUE THREAD

**Issue by miemiemiemiao** [zjns/BiliRoamingX-integrations#13]
### 系统版本

coloros 5.2.1

### Android 版本

8.1

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.41.0

### 问题描述

只要加载视频就会卡在加载界面后闪退 但是声音是正常的 从7.38.0的第二个版本就开始了

### 复现步骤

点击视频或加载视频

### 日志

没有产生日志 这个好像是系统问题()
![Screenshot_2023-08-03-06-03-50-32](https://github.com/zjns/BiliRoamingX-integrations/assets/139220006/5105066c-36c6-4b7f-8adb-1b60c7ebf764)

**Comment by zjns** [comment]
需要遇到同样问题的用户提供日志。
