### ISSUE TITLE
直播屏蔽

### ISSUE THREAD

**Issue by wrrain** [zjns/BiliRoamingX-integrations#130]
### 原因

在哔哩哔哩的搜索结果展示中，有时会插入一些直播页面在视频展示列表中。手动选择“不感兴趣”容易误触，并且即使选择了也不会减少展示的数量。

### 功能简述

可以屏蔽不相关的内容插入。

### 功能逻辑

在设置中，可以手动选择关闭页面插入的展示功能。

**Comment by zjns** [comment]
已经有了

**Comment by wrrain** [comment]
> 已经有了

请问在哪里?

**Comment by zjns** [comment]
> > 已经有了
> 
> 请问在哪里?

记错了，搜什么会出现直播，给个关键词

**Comment by wrrain** [comment]
> > > 已经有了
> > 
> > 
> > 请问在哪里？
> 
> 记错了，搜什么会出现直播，给个关键词

例如搜索关键词：“我的世界”。
