### ISSUE TITLE
Can't share to QQ or WeChat/Weixin

### ISSUE THREAD

**Issue by SinhoMoeme** [zjns/BiliRoamingX-integrations#132]
### 系统版本

Android 14 (AP1A.240305.019.A1)

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.70.0

### 问题描述

漫游X打开净化分享功能，分享任意视频，如分享到微信，显示签名不正确；如分享到QQ，显示非官方应用。分享失败。

### 复现步骤

1.打开漫游X里的净化分享功能；
2.重启bilibili，让设置生效；
3.打开一个视频；
4.分享到QQ或微信；
5.看到来自QQ或微信的报错。

### 日志

[old_log.txt](https://github.com/zjns/BiliRoamingX-integrations/files/14849595/old_log.txt)
[log.txt](https://github.com/zjns/BiliRoamingX-integrations/files/14849598/log.txt)

### 截图或录屏

![Screenshot_20240403-165103](https://github.com/zjns/BiliRoamingX-integrations/assets/112635703/71a12fc4-2de8-493b-a198-02ed15d43576)
![Screenshot_20240403-165120](https://github.com/zjns/BiliRoamingX-integrations/assets/112635703/5f34126f-5277-4595-9887-ffd9f261857b)

### 补充信息

BV1qt421n7wk

**Comment by zjns** [comment]
这是直接修改包的通病，不是我能解决的，但下个版本会提供一个折中的办法。
