### ISSUE TITLE
用着用着会闪退

### ISSUE THREAD

**Issue by piaoying9** [zjns/BiliRoamingX-integrations#137]
### 系统版本

HyperOS

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.70.0

### 问题描述

用着用着会出现闪退的情况，一天好几次

### 复现步骤

打开，刷视频，刷着刷着会出现闪退的情况

### 日志

[log.txt](https://github.com/zjns/BiliRoamingX-integrations/files/14897514/log.txt)

### 截图或录屏

忘记录了

### 解决办法

无

### 补充信息

任何视频都可能

**Comment by zjns** [comment]
是我这儿的包吗？还有在我的包基础上瞎改的

**Comment by piaoying9** [comment]
> 是我这儿的包吗？还有在我的包基础上瞎改的

对，是这儿的，在bb_show频道下载的

**Comment by zjns** [comment]
漫游杂项设置里面开启允许三方APP访问私有存储，然后用MT管理器添加本地存储，打开类似这样的目录 /storage/2963-2D9D/data/files/tombstones 把这下面的文件压缩打包发到这来。

**Comment by piaoying9** [comment]
> 漫游杂项设置里面开启允许三方APP访问私有存储，然后用MT管理器添加本地存储，打开类似这样的目录 /storage/2963-2D9D/data/files/tombstones 把这下面的文件压缩打包发到这来。

[Uploading tombstones.zip…]()

**Comment by piaoying9** [comment]
> 漫游杂项设置里面开启允许三方APP访问私有存储，然后用MT管理器添加本地存储，打开类似这样的目录 /storage/2963-2D9D/data/files/tombstones 把这下面的文件压缩打包发到这来。

[tombstones.zip](https://github.com/zjns/BiliRoamingX-integrations/files/14897620/tombstones.zip)

**Comment by zjns** [comment]
都是native crash，基本上都在使用三个小时左右崩溃，系统或者APP本身的兼容性问题，不是模块引起的，一个建议就是少刷B站。
