### ISSUE TITLE
bug: 频繁闪退

### ISSUE THREAD

**Issue by hhhhhhbit** [zjns/BiliRoamingX-integrations#140]
### 系统版本

miui14.0.8

### Android 版本

13

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.70.0

### 问题描述

老是过个大概半个小时闪退一次

### 复现步骤

就是看着视频或者看评论等任何事情都有可能闪退

### 日志

[log.txt](https://github.com/zjns/BiliRoamingX-integrations/files/14986463/log.txt)

**Comment by zjns** [comment]
漫游杂项设置里面开启允许三方APP访问私有存储，然后用MT管理器添加本地存储，打开类似这样的目录 /storage/2963-2D9D/data/files/tombstones 把这下面的文件压缩打包发到这来。

**Comment by zjns** [comment]
没有提供有效的日志。
