### ISSUE TITLE
首页双列取消单列

### ISSUE THREAD

**Issue by indefinabl** [zjns/BiliRoamingX-integrations#142]
### 原因

打开首页，(设置的是双列模式)，第一个视频必然是单列的，非常不协调

### 功能简述

希望打开首页，强制所有视频都是双列

### 功能逻辑

无

### 实现参考

无

**Comment by zjns** [comment]
不懂你意思，截个图说明下呢，最上面的是横幅banner，不是视频呀

**Comment by indefinabl** [comment]
就像这样，每次打开首页第一个视频就是圈中的这样(图1)，如果能和play版一样(图二)，首页全是双列就好了![Screenshot_2024-04-17-18-00-55-463_tv.danmaku.bili-edit.jpg](https://github.com/zjns/BiliRoamingX-integrations/assets/155245524/8fdf2673-585b-46d8-9cf5-6dc03f71fcb8)

![Screenshot_2024-04-17-18-01-41-079_com.bilibili.app.in.jpg](https://github.com/zjns/BiliRoamingX-integrations/assets/155245524/8302d7f0-c69e-46d3-8f6e-707ed3c32198)

**Comment by zjns** [comment]
首页推荐设置 -> 关闭自动播放 或者 漫游X首页推荐按类型过滤勾选大卡

**Comment by indefinabl** [comment]
非常棒，十分感谢，补充还需要关闭轮播图![add408bbd00521fcc5ed7bc9bfba4db46e4b8ad1e80e037f39c3c5bf86d8b403_122308.gif](https://github.com/zjns/BiliRoamingX-integrations/assets/155245524/9662d4bf-da45-42fe-b447-6b897aded17d)

**Comment by zjns** [comment]
> 非常棒，十分感谢，补充还需要关闭轮播图![add408bbd00521fcc5ed7bc9bfba4db46e4b8ad1e80e037f39c3c5bf86d8b403_122308.gif](https://private-user-images.githubusercontent.com/155245524/323190933-9662d4bf-da45-42fe-b447-6b897aded17d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNTE4MjUsIm5iZiI6MTcxMzM1MTUyNSwicGF0aCI6Ii8xNTUyNDU1MjQvMzIzMTkwOTMzLTk2NjJkNGJmLWRhNDUtNDJmZS1iNDQ3LTZiODk3YWRlZDE3ZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QxMDU4NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzgxNjRjN2NiOGZiY2YxMDNkMDAzOTQxZDNkNmU5YmM4NGIxYTExZjMwNzY0OTg2YjhhODJkMzc4N2ZjZWZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TOYkCD1V7MlMrNbFTNTILukfOinmJPPuDwX0pxnDMb4) [ ![add408bbd00521fcc5ed7bc9bfba4db46e4b8ad1e80e037f39c3c5bf86d8b403_122308.gif](https://private-user-images.githubusercontent.com/155245524/323190933-9662d4bf-da45-42fe-b447-6b897aded17d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNTE4MjUsIm5iZiI6MTcxMzM1MTUyNSwicGF0aCI6Ii8xNTUyNDU1MjQvMzIzMTkwOTMzLTk2NjJkNGJmLWRhNDUtNDJmZS1iNDQ3LTZiODk3YWRlZDE3ZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QxMDU4NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzgxNjRjN2NiOGZiY2YxMDNkMDAzOTQxZDNkNmU5YmM4NGIxYTExZjMwNzY0OTg2YjhhODJkMzc4N2ZjZWZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TOYkCD1V7MlMrNbFTNTILukfOinmJPPuDwX0pxnDMb4) ](https://private-user-images.githubusercontent.com/155245524/323190933-9662d4bf-da45-42fe-b447-6b897aded17d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNTE4MjUsIm5iZiI6MTcxMzM1MTUyNSwicGF0aCI6Ii8xNTUyNDU1MjQvMzIzMTkwOTMzLTk2NjJkNGJmLWRhNDUtNDJmZS1iNDQ3LTZiODk3YWRlZDE3ZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QxMDU4NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzgxNjRjN2NiOGZiY2YxMDNkMDAzOTQxZDNkNmU5YmM4NGIxYTExZjMwNzY0OTg2YjhhODJkMzc4N2ZjZWZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TOYkCD1V7MlMrNbFTNTILukfOinmJPPuDwX0pxnDMb4) [ ](https://private-user-images.githubusercontent.com/155245524/323190933-9662d4bf-da45-42fe-b447-6b897aded17d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNTE4MjUsIm5iZiI6MTcxMzM1MTUyNSwicGF0aCI6Ii8xNTUyNDU1MjQvMzIzMTkwOTMzLTk2NjJkNGJmLWRhNDUtNDJmZS1iNDQ3LTZiODk3YWRlZDE3ZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QxMDU4NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzgxNjRjN2NiOGZiY2YxMDNkMDAzOTQxZDNkNmU5YmM4NGIxYTExZjMwNzY0OTg2YjhhODJkMzc4N2ZjZWZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TOYkCD1V7MlMrNbFTNTILukfOinmJPPuDwX0pxnDMb4)

过滤类型勾选轮播图就行了

**Comment by zjns** [comment]
> 还需要关闭轮播图

过滤类型选择轮播图就行了
