### ISSUE TITLE
可以尝试解锁杜比全景声以及HI-RES嘛 

### ISSUE THREAD

**Issue by Blueberryprawn** [zjns/BiliRoamingX-integrations#15]
### 原因

双杜比片源以及HI-RES目前仍然需要大会员才能开启

### 功能简述

解锁杜比全景声和HI-RES

### 功能逻辑

程序原界面已有该部分

**Comment by zjns** [comment]
别做梦了，能让你无限试看大会员画质都是阿B的施舍，接口没做限制罢了。非会员拿不到hi-res音源地址的。
