### ISSUE TITLE
feat: 不从 PCDN 加载资源

### ISSUE THREAD

**Issue by PuerNya** [zjns/BiliRoamingX-integrations#17]
### 原因

PCDN 和 MCDN 是坏文明

### 功能简述

隔壁漫游推出的 不从 PCDN 加载资源

### 功能逻辑

开关打开即可

### 实现参考

哔哩漫游的两个 commit： [a5bdac9](https://github.com/yujincheng08/BiliRoaming/commit/a5bdac9f2a2bff1e8569546b2a8260f91360d5a0)  和 [7339d2a](https://github.com/yujincheng08/BiliRoaming/commit/7339d2a3b631610f53c23830f6915a2b14322aa3)

**Comment by zjns** [comment]
是遇到了视频播放问题？

**Comment by zjns** [comment]
没有充足理由，因此关闭。
