### ISSUE TITLE
bug: 动态会刷出好几天前的视频

### ISSUE THREAD

**Issue by yongrenx** [zjns/BiliRoamingX-integrations#20]
### 系统版本

MIUI14

### Android 版本

13

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.42.0

### 问题描述

一段时间没打开软件会出现这个bug，比如隔一晚，不知道是原版还是修改版的bug

### 复现步骤

隔一段时间后打开app

### 日志

[log.txt](https://github.com/zjns/BiliRoamingX-integrations/files/12327006/log.txt)

### 截图或录屏

![IMG_20230812_170020](https://github.com/zjns/BiliRoamingX-integrations/assets/120461815/353fc75a-e55d-4620-8128-dd5b5c3c0691)

**Comment by zjns** [comment]
要不你先排除下是不是修改版的问题？

**Comment by yongrenx** [comment]
> 要不你先排除下是不是修改版的问题？

因为目前没在其他地方看到有说这个bug的，所以先发这边了，之后会测下普通版有没有这个bug

**Comment by yongrenx** [comment]
> 要不你先排除下是不是修改版的问题？
普通版目前测试没出现这个bug
