### ISSUE TITLE
bug: 竖屏模式广告屏蔽失效

### ISSUE THREAD

**Issue by NaNaChiSama** [zjns/BiliRoamingX-integrations#204]
### 系统版本

ColorOS 14

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.77.0

### 问题描述

竖屏模式的广告屏蔽似乎失效了？现在在竖屏模式下有几率刷出这种推广视频

### 复现步骤

1.打开哔哩哔哩
2.点击竖屏模式
3.开刷

### 日志

暂时没抓到日志，这玩意儿的出现频率似乎挺低的，开了调试模式之后又刷了半个小时都没再遇到这种推广

### 截图或录屏

![Screenshot_2024-05-07-10-54-33-24_149003a2d400f6adb210d7e357a3a646](https://github.com/BiliRoamingX/BiliRoamingX/assets/97809275/e607c429-aab5-462c-a0a2-d277fe9724f6)

### 补充信息

BV1ym411B77v

**Comment by zjns** [comment]
那等你开启调试模式刷到了再说吧

**Comment by mlminge** [comment]
> 那等你开启调试模式刷到了再说吧

那个首页轮播广告突然出现是bug吗？已经打开了屏蔽，但是现在每次都在了，只要重新打开b站就必定会在首页出现，并且刷新还在，越刷越多。། – _ – །
![Screenshot_2024-05-07-19-57-26-81_149003a2d400f6adb210d7e357a3a646](https://github.com/BiliRoamingX/BiliRoamingX/assets/169157702/4a9f8309-0110-4aa1-8a4b-4c20bbbadde7)
