### ISSUE TITLE
在高版本中开启取消自动订阅合集

### ISSUE THREAD

**Issue by HSSkyBoy** [zjns/BiliRoamingX-integrations#207]
### 系统版本

鸿蒙4.0.0.118

### AOSP 版本

12

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.77.0

### 问题描述

在最新版本中取消自动订阅合集仍然有效

### 复现步骤

先安装7.42.0版本的Bilibili Revanced，然后在设置里打开取消自动订阅合集，再安装最新构建版，那么虽然设置里强制关闭了这个选项的开启，但是功能依旧有效。

### 日志

更新应用日志清空了

### 解决办法

允许启用此功能(bushi

### 补充信息

由 TG@Re_Area_0 率先发现并公布此问题

**Comment by zjns** [comment]
怎么看出来有效的，新版本来就不会自动订阅合集

**Comment by HSSkyBoy** [comment]
> 怎么看出来有效的，新版本来就不会自动订阅合集

ଲଇଉକ捂脸……
