### ISSUE TITLE
feat: 隐藏评论区的IP属地

### ISSUE THREAD

**Issue by WangYi640** [zjns/BiliRoamingX-integrations#22]
### 原因

![20230819163410](https://github.com/zjns/BiliRoamingX-integrations/assets/132351967/20cb6950-30ba-48e2-b63d-368b7cc6addd)
IP属地会分散看评论正文的注意力 容易造成地域黑和刻板印象 影响使用体验

### 功能简述

增加一个关闭 IP属地 的按钮

### 功能逻辑

关闭IP属地显示

**Comment by zjns** [comment]
过于强迫症。
