### ISSUE TITLE
feat: 请求添加“去除直播p2p”

### ISSUE THREAD

**Issue by IA20201** [zjns/BiliRoamingX-integrations#23]
### 原因

叔叔没🐴，白嫖带宽

### 功能简述

去除直播p2p cdn

### 功能逻辑

叔叔飞🐴

### 实现参考

![Screenshot_2023-08-22-16-28-05-095_com bilibili app in-edit](https://github.com/zjns/BiliRoamingX-integrations/assets/75969201/3178eb0f-63a4-46f1-b6c7-e0829ca1e623)

**Comment by zjns** [comment]
感觉没啥用，不弄。
