### ISSUE TITLE
feat: 视频封面保存功能

### ISSUE THREAD

**Issue by SoliloQuizee** [zjns/BiliRoamingX-integrations#24]
### 原因

有些视频的封面很好看但是没法保存下来

### 功能简述

获取到视频封面的图片然后保存下来

### 功能逻辑

比如长按保存这种

### 实现参考

以前的漫游好像有过这个功能，后来不知道怎么去掉了

**Comment by zjns** [comment]
已实现，可以通过视频简介长按自由复制保存，仅支持新版播放器。
