### ISSUE TITLE
feat: 想要有音频和字幕的下载

### ISSUE THREAD

**Issue by mgcccc** [zjns/BiliRoamingX-integrations#26]
### 原因

找到一个hires音频的视频，想直接把音频下载下来

### 功能简述

想要下载视频的音频

### 功能逻辑

在缓存选项内加一个音频

### 实现参考

漫游X有该功能，没在内置版找到

**Comment by zjns** [comment]
漫游X哪里有这功能了？之前就试过，不集成ffmpeg不行，APP自带的ffmpeg不能解包容器提取flac，Android系统API也没有相关支持，但如果集成ffmpeg，APP体积暴涨，建议用三方工具，例如yt-dlp。
