### ISSUE TITLE
7.46版本默认播放速度失效

### ISSUE THREAD

**Issue by rabbit2099** [zjns/BiliRoamingX-integrations#28]
### 系统版本

MIUI14

### Android 版本

13

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.46

### 问题描述

7.46版本默认播放速度失效

### 复现步骤

设置了默认速度还是失效

### 日志

123

**Comment by zjns** [comment]
无法复现，新旧播放器都是生效的。
