### ISSUE TITLE
feat: 需要下载会员画质视频

### ISSUE THREAD

**Issue by mgcccc** [zjns/BiliRoamingX-integrations#31]
### 原因

视频无法下载会员画质

### 功能简述

视频想要下载会员画质

### 功能逻辑

下载里选择会员画质下载视频

### 实现参考

用漫游x试了试，可以下载会员画质

**Comment by zjns** [comment]
如果不是会员，通过播放器某实验性功能开启会员画质，则是有意不允许下载会员画质，会员则无此限制。
