### ISSUE TITLE
通知栏播放器问题

### ISSUE THREAD

**Issue by opbmniop** [zjns/BiliRoamingX-integrations#34]
### 原因

各项设置都看了一遍发现没法跟原版一样有通知栏播放器和锁屏播放器（如图）
[https://img1.imgtp.com/2023/09/22/Xneb7kmW.jpg](url)
[https://img1.imgtp.com/2023/09/22/6Im8QNFz.jpg](url)

### 功能简述

不知道是哪里出了问题，或求一个处理方法

### 功能逻辑

.

**Comment by zjns** [comment]
杂项 - 原生音乐通知样式，如果开了之后反而没通知，建议关掉
