### ISSUE TITLE
bug: 播放受限番剧闪退

### ISSUE THREAD

**Issue by 114511e** [zjns/BiliRoamingX-integrations#35]
### 系统版本

鸿蒙4.0.0.116/115

### Android 版本

鸿蒙4.0.0.116/115

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.46.0

### 问题描述

追番（港澳台）无法进入看番

### 复现步骤

1.打开追番（港澳台）
2.点击进入一个番剧
3.进入后会闪退/无响应/突然退出

### 日志

[log.txt](https://github.com/zjns/BiliRoamingX-integrations/files/12707775/log.txt)
[log(1).txt](https://github.com/zjns/BiliRoamingX-integrations/files/12707776/log.1.txt)

**Comment by zjns** [comment]
可通过更新可用解析服务器临时解决闪退问题。
