### ISSUE TITLE
feat: 链接文本转换为超链接

### ISSUE THREAD

**Issue by lxl141421** [zjns/BiliRoamingX-integrations#36]
### 原因

视频简介里或者评论区里作者留下的文本链接需要重新复制才能跳转，有点麻烦。

### 功能简述

能否通过正则表达式转换为超链接，方便快速访问跳转。

### 功能逻辑

网页版有实现此功能的脚本，链接放到了“实现参考”里，希望有所帮助。

### 实现参考

https://greasyfork.org/zh-CN/scripts/452150-textlink-to-hyperlink

**Comment by zjns** [comment]
可通过长按复制选中链接用其他方式打开。
