### ISSUE TITLE
bug: 动态页过滤失效

### ISSUE THREAD

**Issue by Yumipk** [zjns/BiliRoamingX-integrations#38]
### 系统版本

MIUI13

### Android 版本

11

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.49

### 问题描述

哔哩漫游x动态页设置问题，
①打开屏蔽无权查看冲电动态，(动态还是有充电动态
②移除热门话题(综合)  ，动态页照常显示

### 复现步骤

打开哔哩哔哩里
点击动态
刷新

### 日志

空

### 解决办法

/

**Comment by zjns** [comment]
已修复，等下个版本。
