### ISSUE TITLE
默认播放速度失效

### ISSUE THREAD

**Issue by rabbit2099** [zjns/BiliRoamingX-integrations#39]
### 系统版本

MIUI14

### Android 版本

13

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.49

### 问题描述

设置默认播放速度失效，如1.5，视频页面还是1.0，回退7.44正常，7.46也失效

### 复现步骤

设置默认播放速度失效，如1.5，视频页面还是1.0

### 日志

上传失败，如果需要我电脑试试

**Comment by zjns** [comment]
在我的OneUI Android13上无法复现，不知道是不是跟系统有关系。

**Comment by rabbit2099** [comment]
我通过把默认分辨率从默认改到其他之后，默认播放速度生效了，你设置了默认分辨率吗，这也许是一个bug

> 在我的OneUI Android13上无法复现，不知道是不是跟系统有关系。
