### ISSUE TITLE
bug: 分享失败以及直播无画面

### ISSUE THREAD

**Issue by Fool-King** [zjns/BiliRoamingX-integrations#42]
### 系统版本

HarmonyOS

### Android 版本

12

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

1.11

### 问题描述

通过微信分享时提示“签名不对，请检查签名是否与开放平台上填写的一致”，分享失败；QQ分享没有问题。
有一个直播间出现了能看见弹幕，看不见画面（一直显示“正在缓冲…”）的情况，但是其他几个直播间没有问题。

### 复现步骤

1.分享 通过微信
2.进入直播间

### 日志

[log.txt](https://github.com/zjns/BiliRoamingX-integrations/files/12783054/log.txt)

### 截图或录屏

![Screenshot_20231002_213159_tv danmaku bili](https://github.com/zjns/BiliRoamingX-integrations/assets/62875591/6e9d436e-0f50-480a-8e67-152deb54fcd4)
![Screenshot_20231002_213150_tv danmaku bili](https://github.com/zjns/BiliRoamingX-integrations/assets/62875591/da904043-3fe6-4b1d-8d8c-5d0edbb98c9c)

**Comment by zjns** [comment]
微信不能分享是预期行为，直播间无画面应该是网络或者up主推流问题。
