### ISSUE TITLE
feat: play版本支持

### ISSUE THREAD

**Issue by YaeSakuraQvQ** [zjns/BiliRoamingX-integrations#44]
### 原因

不太喜欢国内版的一些东西...感觉用下来play版更清爽流畅
(之前的漫游x并未失效，但听说大佬基于revanced方案的改包性能更好，所以希望也支持到play版)

话说这个性能是只比lspatch内置好，还是也优于lsp框架呢...~~如果lsp框架更好那就先不用整了~~

### 功能简述

添加基于GooglePlay版的构建

### 功能逻辑

添加基于GooglePlay版的构建

**Comment by zjns** [comment]
这只是我个人凭爱好维护的项目，添加play版本支持就意味着花费更多精力和时间维护，所以暂时不考虑支持play版本。

**Comment by YaeSakuraQvQ** [comment]
或许你有空时可以考虑做一个版本(比如我现在用的3.16就感觉不错)，没必要时刻跟着版本号去更新，也可以说明不接play版的issue(除恶性bug)，就当给大家多一个选择
当然如果你实在没时间，那就先不做吧，之前的漫游x还可以用
最后赞美大佬~感谢大佬带来这么好的模块
Kofua ***@***.***> 于2023年10月12日周四 19:15写道：
