### ISSUE TITLE
[Feature]首页推荐视频屏蔽粉丝数较少，但是投稿视频数较大uo主或视频

### ISSUE THREAD

**Issue by ghost** [zjns/BiliRoamingX-integrations#494]
### 原因

经常会在首页上面刷到一些低质视频，点开一看全是脚本投稿的账号，粉丝数还没有投稿数多，但是这种视频经常会被推到首页上面，很烦

### 功能简述

就是在首页视频推荐过滤的时候，可以屏蔽粉丝数较少的up主，和投稿视频较多的账号，比如几千个投稿视频，但是只有几千粉丝的那种账号

### 功能逻辑

在首页视频过滤中添加这样的规则，屏蔽粉丝数少于多少的账号，屏蔽投稿件数大于多少的账号，
可以的话再加上粉丝数少于多少and投稿件数＞多少

**Comment by zjns** [comment]
接口没有相关数据，必须要另外请求接口获取相关数据，性能会大幅下降，不可取，考虑移除低播放量的视频
