### ISSUE TITLE
[Feature] 请求对评论区 "大家都在搜：" 的横条的屏蔽

### ISSUE THREAD

**Issue by Norca0721** [zjns/BiliRoamingX-integrations#496]
### 原因

![1](https://github.com/user-attachments/assets/26e3524f-5ff5-40cb-aafe-d944bbaad8b8)

这个蓝色放大镜真碍眼吧，貌似在首页顶部的热门标签的视频都会有这个

### 功能简述

![2](https://github.com/user-attachments/assets/deae4ab4-b6bb-47bf-a3c2-4cd75081ac08)

屏蔽掉这个横条

### 功能逻辑

哔哩漫游X-视频详情页-评论 添加 "屏蔽大家都在搜"

**Comment by zjns** [comment]
调试模式复现把日志贴到这

**Comment by Norca0721** [comment]
[log_哔哩哔哩.zip](https://github.com/user-attachments/files/17164214/log_.zip)

**Comment by zjns** [comment]
日志无效

**Comment by Norca0721** [comment]
神秘，开着调试模式导出来的log是空的，不管了

**Comment by cxw620** [comment]
> 神秘，开着调试模式导出来的log是空的，不管了

给个视频BV号看看?

**Comment by Norca0721** [comment]
> > 神秘，开着调试模式导出来的log是空的，不管了
> 
> 给个视频BV号看看?

首页顶部的热门标签的很多视频都会有这个
感觉是tag里有个热门tag就会有这个横条
