### ISSUE TITLE
[BUG] 打开"收到回复"闪退

### ISSUE THREAD

**Issue by HSSkyBoy** [zjns/BiliRoamingX-integrations#498]
### 系统版本

鸿蒙4.2.0

### Android 版本

12

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.15.0(8150200)

### 问题描述

最新版本 并且获得消息界面云测
打开"收到回复"闪退

### 复现步骤

见视频

### 日志

[log_哔哩.zip](https://github.com/user-attachments/files/17172808/log_.zip)

### 截图或录屏

https://github.com/user-attachments/assets/d5ba69a0-2a07-41f7-879d-e0c36680978f

### 补充信息

漫游X版本 v1.23.3.r2044

**Comment by zjns** [comment]
b站的问题吧，原版试试呢

**Comment by zjns** [comment]
或者用8150400看看，你这不是市场最新包

**Comment by HSSkyBoy** [comment]
> 或者用8150400看看，你这不是市场最新包

![log_哔哩哔哩.zip](https://github.com/user-attachments/files/17174182/log_.zip)

更新到新版本仍旧会出现此问题 估计不是b站本身的问题 暂时不确定是哪个功能 没从日志中看出来

**Comment by HSSkyBoy** [comment]
> 或者用8150400看看，你这不是市场最新包

![log_哔哩哔哩.zip](https://github.com/user-attachments/files/17174182/log_.zip)

更新到新版本仍旧会出现此问题 估计不是b站本身的问题 暂时不确定是哪个功能 没从日志中看出来

**Comment by zjns** [comment]
看日志跟模块是没关系的
