### ISSUE TITLE
feat: 关闭请求开启推荐个性化内容的弹窗

### ISSUE THREAD

**Issue by qingmu0417** [zjns/BiliRoamingX-integrations#50]
### 原因

在设置中关闭推荐个性化内容后，经常会有请求打开个性化推荐内容的弹窗，就跟青少年弹窗一样很烦，但是大多数人一般都选择推荐个性化内容所以没有遇到过这个弹窗，但是我不想被B站信息茧房又很烦恼这个弹窗

### 功能简述

类似关闭青少年弹窗一样的设置，放在杂项里关闭青少年弹窗下面

### 功能逻辑

一键关闭就行

**Comment by zjns** [comment]
长啥样式，截个图看看呢

**Comment by qingmu0417** [comment]
> 长啥样式，截个图看看呢

你在推荐设置里面关闭推荐我可能感兴趣的内容，就能见到请求打开个性化内容推荐的弹窗了，出现时间不定，不是每次打开都有的

**Comment by qingmu0417** [comment]
![Screenshot_20231019_191654_tv danmaku bili](https://github.com/zjns/BiliRoamingX-integrations/assets/145129567/7e95205d-358f-4f36-80bd-f2fcab106e73)

**Comment by qingmu0417** [comment]
> ![Screenshot_20231019_191654_tv danmaku bili](https://user-images.githubusercontent.com/145129567/276595678-7e95205d-358f-4f36-80bd-f2fcab106e73.jpg)

我找到了其他人视频里面的弹窗，我记得弹窗位置有的时候在底部有的时候在顶部
