### ISSUE TITLE
[BUG] 直播间状态栏在全屏后后，没有隐藏隐藏

### ISSUE THREAD

**Issue by danyuan1010** [zjns/BiliRoamingX-integrations#509]
### 系统版本

oneui6.1.1

### Android 版本

14

### 哔哩哔哩版本

HD 版

### 哔哩哔哩版本号

1.47.0

### 问题描述

进入直播间后点击全屏后，状态栏没有收起，而是遮挡在弹幕和画面上。测了一下只有HD版这样。

### 复现步骤

进入直播间后点击全屏后

### 日志

[log_咩哩咩哩HD.zip](https://github.com/user-attachments/files/17269163/log_.HD.zip)

### 截图或录屏

![Uploading Screenshot_20241006_192720_HD.jpg…]()

**Comment by zjns** [comment]
非模块问题
