### ISSUE TITLE
[Feature] 添加功能以禁止弹幕折叠计数的开启

### ISSUE THREAD

**Issue by washingtea** [zjns/BiliRoamingX-integrations#510]
### 原因

在b站7.0更新这一功能后极大破坏了弹幕体验，并且还难以找到可用的将其完全禁用的方案

### 功能简述

在漫游设置中开启该功能后在会开启弹幕折叠计数的视频中禁止自动开启折叠技术

### 功能逻辑

在漫游设置页添加一项按钮

### 实现参考

在打开可能会触发折叠计数的视频时检测开关的开启状态，如果开启则将其关闭（笨办法）

**Comment by zjns** [comment]
个人觉得计数折叠弹幕没什么不好，不存在破坏体验一说
