### ISSUE TITLE
〔Feature〕HD端请求增加可设置视频详细页退后一级后操作逻辑

### ISSUE THREAD

**Issue by Lockysolucky** [zjns/BiliRoamingX-integrations#515]
### 原因

    描述：在HD版本中，在视频详细页，视频下方会有推荐视频栏，点击任意视频，进行退后一级的操作时，操作逻辑是直接退回到首页，影响观看视频的体验（原HD端就是这样的）。
    [原因：当用户想观看多个推荐视频时，点击任意视频后无法回到原视频详细页。]

https://github.com/user-attachments/assets/782fe290-a67d-405f-bb3b-77a71d92f0a8

### 功能简述

使用户能够设置视频详细页退后一级后的操作逻辑，可选择回到首页或回到上个视频的详细页。

### 功能逻辑

在漫游设置栏/视频详细页，当中增加一个设置选项，选择首页/退回上一视频详细页，使得用户能够设置视频退后一级后的操作逻辑，可选择回到首页或回到上个视频的详细页。

### 实现参考

原哔哩哔哩移动端（非HD版）仅包括该功能，并未有相关设置。

**Comment by zjns** [comment]
无法实现
