### ISSUE TITLE
在评论审查报告中指出被阿瓦隆屏蔽的关键词

### ISSUE THREAD

**Issue by Helvetica1963** [zjns/BiliRoamingX-integrations#521]
### 原因

发的评论被awl吞了，但不知道为什么吞，一句一句删除排查太费时间，反复试验还会触发awl限制升级，最后啥也发不了

### 功能简述

如题，或提供一个屏蔽词的参考表

### 功能逻辑

在审查结果弹窗中标出触发屏蔽的语句，或在漫游x设置中增加一个页面显示可查阅的awl屏蔽词库

**Comment by zjns** [comment]
获取不到相应的违禁词
