### ISSUE TITLE
[BUG] 使用搜索框搜索到的评论无法打开

### ISSUE THREAD

**Issue by wyi6** [zjns/BiliRoamingX-integrations#523]
### 系统版本

origin os 2

### Android 版本

11

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.14       3.19.2

### 问题描述

粉版和play版均有此问题

https://github.com/user-attachments/assets/c5d53d46-c3d0-4183-ad8b-7e3bcaa6d88a

https://github.com/user-attachments/assets/c908097f-419a-4660-ac5c-0b02feb2f36e

### 复现步骤

1.打开客户端使用搜索功能
2.搜索任意内容
3.无法点入任何搜索到的评论

专栏可以正常点击进入 动态也可以 但评论不行

### 日志

－

### 解决办法

可能是强行调用原生界面所引起的

**Comment by zjns** [comment]
无法复现，日志也没有
