### ISSUE TITLE
[Feature] 希望版权内容在动态页添加稍后再看功能

### ISSUE THREAD

**Issue by cbf1999** [zjns/BiliRoamingX-integrations#526]
### 原因

当前的站内版权内容（番剧，国创，影视，电视剧，纪录片，综艺）若以【动态】方式显示，点击右上角无法添加【稍后再看】
![Screenshot_2024-10-18-09-20-08-277_tv danmaku bili](https://github.com/user-attachments/assets/bae76fcc-6c96-414d-a5a8-3463352aa474)
只能够通过点进官方账号的空间，在视频列表中添加【稍后再看】
![Screenshot_2024-10-18-09-18-10-099_tv danmaku bili](https://github.com/user-attachments/assets/458d6cbd-c9ef-453f-a282-0d4ce1ced6db)

### 功能简述

希望可以在动态页，点击右上角的三个点，弹出的功能框中（如下图页面）添加【添加到稍后再看】功能
![Screenshot_2024-10-18-09-20-08-277_tv danmaku bili](https://github.com/user-attachments/assets/c97800e7-83ff-4d77-9577-8e37252ec6ff)

### 功能逻辑

无

### 实现参考

以往app版本版权内容是无法添加稍后在看的，现版本已经可以了，但是官方一直没有在动态页上添加这个按钮，每次想添加都好麻烦。功能是已经可以实现了，只是少一个比较方便的按钮，不知道实现起来麻不麻烦……
![9bb24495f30ac017c3e91181e826a2e](https://github.com/user-attachments/assets/88fabb84-2e31-41d4-94c2-d7c56e6125af)

**Comment by zjns** [comment]
默认添加菜单，没有开关
