### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ghost** [zjns/BiliRoamingX-integrations#527]
### 系统版本

鸿蒙3

### Android 版本

10

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.9.0

### 问题描述

点击主页头像跳转到我的页  设置的是主页头像打开看视频

### 复现步骤

- 打开主页头像跳转看视频
- 点击主页头像

### 日志

[log.txt](https://github.com/user-attachments/files/17444936/log.txt)

**Comment by zjns** [comment]
日志无效，无法复现
