### ISSUE TITLE
[Feature] 能否屏蔽直播间左下角投票弹窗

### ISSUE THREAD

**Issue by zhyh12** [zjns/BiliRoamingX-integrations#529]
### 原因

直播间主播发起投票后左下角会有弹窗，就算右下角投完票，退出直播间再进，左下角还是有弹窗
![IMG_20241019_211038](https://github.com/user-attachments/assets/ffc854e8-9293-441a-bc58-868d268182c0)

### 功能简述

能否屏蔽直播间左下角投票弹窗

### 功能逻辑

1

### 实现参考

1

**Comment by zjns** [comment]
试试屏蔽直播效果打分

**Comment by zhyh12** [comment]
> 试试屏蔽直播效果打分

不行，净化直播间浮窗全都已经开了，血狼破军直播间现在还在投票，你可以去看看
