### ISSUE TITLE
bug: 深色模式开屏有白色部分

### ISSUE THREAD

**Issue by Mewdes** [zjns/BiliRoamingX-integrations#53]
### 系统版本

Harmony OS4

### Android 版本

12

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.50(1.12)

### 问题描述

当系统进入深色模式，开屏页是深色页中套着一个白底图标

### 复现步骤

1.打开系统深色模式
2.点击哔哩哔哩

### 日志

[log.txt](https://github.com/zjns/BiliRoamingX-integrations/files/13056129/log.txt)

### 截图或录屏

![Screenshot_20231020_234437_tv danmaku bili_edit_50677273353723](https://github.com/zjns/BiliRoamingX-integrations/assets/128128467/4db69740-050c-418c-a881-69d52e64fc9d)

### 解决办法

为这几个功能设置开关也许能解决？
![Uploading Screenshot_20231020_234628_tv.danmaku.bili_edit_50786757611519.jpg…]()

**Comment by Mewdes** [comment]
![Screenshot_20231020_234628_tv danmaku bili_edit_50786757611519](https://github.com/zjns/BiliRoamingX-integrations/assets/128128467/7809fb54-4cce-422c-b62e-e35ad692a2b6)

**Comment by zjns** [comment]
https://github.com/zjns/BiliRoamingX-integrations/releases/download/20231021-debug/Bili-v7.50.0-patched1.12@BBShow-debug.apk 用这个包看看

**Comment by Mewdes** [comment]
感谢您的帮助，但是这个问题没有解决。可能是鸿蒙对安卓特性支持的不再彻底？

**Comment by zjns** [comment]
@Mewdes 再试下这个呢，不行就没辙了 https://github.com/zjns/BiliRoamingX-integrations/releases/download/20231021-debug2/Bili-v7.50.0-patched1.12@BBShow-debug2.apk

**Comment by Mewdes** [comment]
确实没好，不过我就这样用吧，麻烦大佬帮忙debug了。
