### ISSUE TITLE
[Feature] 屏蔽片哥片姐推流及评论

### ISSUE THREAD

**Issue by REcounting** [zjns/BiliRoamingX-integrations#530]
### 原因

最近b站老总死了妈，天天推流片哥片姐，评论区到处都是卖片的，希望能够救救b站

### 功能简述

屏蔽片哥片姐

### 功能逻辑

我也不知道

**Comment by zjns** [comment]
这玩意端侧没有好的办法判断，只有B站下决心服务端判断过滤才行，可以通过关键词、屏蔽低用户等级的评论缓解。
