### ISSUE TITLE
[BUG] 我的页显示空白

### ISSUE THREAD

**Issue by ghost** [zjns/BiliRoamingX-integrations#532]
### 系统版本

鸿蒙3

### Android 版本

10

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.9.0

### 问题描述

"我的"页显示空白

### 复现步骤

点开"我的

### 日志

我的页空白无法导出日志
![Screenshot_20241019_222349_tv danmaku bili_edit_12527111260587](https://github.com/user-attachments/assets/e1f68dc2-97b6-452e-aa90-06a70cbeab9b)

### 截图或录屏

![Screenshot_20241019_222349_tv danmaku bili_edit_12527111260587](https://github.com/user-attachments/assets/8778bf03-24a5-43c3-b83b-5715ee6505f2)

**Comment by zjns** [comment]
无法复现，检查我的页组件过滤是否太狠了，或者是否修改了apk，自己签名了
