### ISSUE TITLE
[BUG] 个性装扮显示问题

### ISSUE THREAD

**Issue by Rude56** [zjns/BiliRoamingX-integrations#535]
### 系统版本

Flyme 11.0.0.0A

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.9.0

### 问题描述

我的首页底栏只展示首页，动态，我的，然后用罗小黑装扮，动态的图标竟然是一个新的图标。如果换成兰溪镇装扮，动态显示的是发布图标

### 复现步骤

1.首页底栏显示首页，动态，我的
2.使用个性装扮（可以去咸鱼买，便宜很多）

### 日志

[log_哔哩哔哩.zip](https://github.com/user-attachments/files/17448230/log_.zip)

### 截图或录屏

![P41020-101213](https://github.com/user-attachments/assets/ddc31e0c-3df1-41d7-bd73-1522a2b51746)
![P41020-101524](https://github.com/user-attachments/assets/8b54426e-ef7b-4fe1-9736-5519c86bf949)

**Comment by Rude56** [comment]
我才发现在杂项里面打开自制主题，就能白嫖

**Comment by zjns** [comment]
![Screenshot_20241020_135053_MT Manager.png](https://github.com/user-attachments/assets/4f3ba94e-32ae-4fbf-9fc7-60007850c09e)

主题本身的问题
