### ISSUE TITLE
[Feature] 恢复旧版的弹幕优选和智能云屏蔽功能

### ISSUE THREAD

**Issue by datou1996** [zjns/BiliRoamingX-integrations#536]
### 原因

以前可以自行选择是否启用这两个功能，现在b站强制开启无法关闭，会屏蔽掉很多有用的弹幕。

### 功能简述

恢复旧版本的弹幕优选和智能云屏蔽功能，并可以手动关闭上述功能。

### 功能逻辑

同旧版本b站app。

**Comment by zjns** [comment]
有了
