### ISSUE TITLE
[BUG] 调试模式无法抓取日志

### ISSUE THREAD

**Issue by wyi6** [zjns/BiliRoamingX-integrations#537]
### 系统版本

origin os 2

### Android 版本

11

### 哔哩哔哩版本

Play 版（国际版）

### 哔哩哔哩版本号

3.19.2

### 问题描述

询问一下，打开调试模式抓不到日志，不知道是不是因为我问题

![Screenshot_20241021_022245](https://github.com/user-attachments/assets/0b2efa8a-e49f-48ac-8b8e-8afb987dc623)

[log_bilibili.zip](https://github.com/user-attachments/files/17451648/log_bilibili.zip)

### 复现步骤

1.打开调试模式抓取日志
2.日志中没有有效信息

### 日志

同上

**Comment by zjns** [comment]
系统阻止了 logcat
