### ISSUE TITLE
[BUG] 1.24.0版无法被npatch打包

### ISSUE THREAD

**Issue by My-Responsitories** [zjns/BiliRoamingX-integrations#538]
### 系统版本

EMUI

### Android 版本

11

### 哔哩哔哩版本

Play 版（国际版）

### 哔哩哔哩版本号

[BiliPlay-v3.19.2-x1.24.0@bb_show.apk](https://github.com/BiliRoamingX/BiliRoamingX-PreBuilds/releases/tag/android_i-v3.19.2-b15154452-p1.24.0)

### 问题描述

1.24.0版无法被npatch打包

### 复现步骤

`BiliPlay-v3.19.2-x1.24.0@bb_show.apk`被npatch`0.6.1(425)`内置模式不嵌入任何模块打包, 去校验方案lv2, 安装后打开1-2秒闪退. 而上一个版本`BiliPlay-v3.19.2-x1.23.3@bb_show.apk`则不会

### 日志

npatch打包无错误
使用`adb logcat -s BiliRoamingX`未捕获到任何信息

### 补充信息

magisk的lsposed可以正常使用模块

**Comment by zjns** [comment]
不支持修改使用
