### ISSUE TITLE
[Feature] 为热门视频提供反馈、拉黑功能

### ISSUE THREAD

**Issue by xovow** [zjns/BiliRoamingX-integrations#541]
### 原因

方便屏蔽不想看的热门视频、up

### 功能简述

像推荐视频点击右下三点一样弹出反馈界面
![Screenshot_20241022_174005_tv danmaku bili_edit_9126267773905339](https://github.com/user-attachments/assets/1f77d5b3-755b-4741-b441-ac9b18114720)
![Screenshot_20241022_174017_tv danmaku bili_edit_9126261634696486](https://github.com/user-attachments/assets/5556bc47-86df-4456-b2f0-751e708afd35)

### 功能逻辑

无

### 实现参考

无

**Comment by xovow** [comment]
老是有不想看的视频出现在热门，又不想点进去屏蔽

**Comment by zjns** [comment]
这弹框一看就不得行

**Comment by xovow** [comment]
> 这弹框一看就不得行

感觉最新版本比上一个版本的启动速度慢了，是因为加了sponsorblock的原因吗

**Comment by xovow** [comment]
> 这弹框一看就不得行

能否实现像[pilipalax](https://github.com/orz12/PiliPalaX)这样的呢
![Screenshot_20241024_190940_com orz12 PiliPalaX_edit_9200194645674266](https://github.com/user-attachments/assets/0d00f538-798e-4828-bfe8-09d4c28c1b8d)
