### ISSUE TITLE
[BUG] 双端跳过广告的时间不一致

### ISSUE THREAD

**Issue by doveyo** [zjns/BiliRoamingX-integrations#546]
### 系统版本

MIUI 12

### Android 版本

10

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.9.0

### 问题描述

电脑上提交的跳过广告，在电脑的Edge浏览器能正常精准的跳过，但是在手机上的跳过会慢一秒。

### 复现步骤

BV1JpyGYQEQ8，双端测试过

### 日志

-

### 截图或录屏

https://github.com/user-attachments/assets/7f7768f1-d851-493c-9d9c-1ffe2985cdcb

### 补充信息

BV1JpyGYQEQ8

**Comment by zjns** [comment]
B站播放器的锅，有时他会强制调整你要跳转的位置，像这条他就会始终往前调整1542ms。
