### ISSUE TITLE
[BUG] 首页右上角活动图标无法正常屏蔽

### ISSUE THREAD

**Issue by zpy2575** [zjns/BiliRoamingX-integrations#547]
### 系统版本

miuihyper

### Android 版本

15

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.9

### 问题描述

开启屏蔽首页右上角热门活动，但是还是会出现。

### 复现步骤

开启功能后还是会出现右上角英雄联盟图标

### 日志

[log_哔哩哔哩.zip](https://github.com/user-attachments/files/17517794/log_.zip)

### 截图或录屏

![Screenshot_2024-10-25-15-16-32-599_tv danmaku bili](https://github.com/user-attachments/assets/57c721c8-35c1-43d3-95c1-8ac853ca0ea9)
![Screenshot_2024-10-25-15-23-27-299_tv danmaku bili](https://github.com/user-attachments/assets/513bc60c-417e-4d7f-ab41-9fbdca9795f2)

**Comment by zjns** [comment]
目前算在游戏中心里的
