### ISSUE TITLE
[Feature] 修改弹幕优选模式弹窗的关闭逻辑

### ISSUE THREAD

**Issue by MiKoto-Railgun** [zjns/BiliRoamingX-integrations#549]
### 原因

B站的弹幕优选模式关闭逻辑就是依托答辩，打开简单，关闭的时候就得去全局设置里关闭，太麻烦了（当时我就觉得是要强推弹幕优选减少弹幕数量，现在一看果然）

### 功能简述

打开弹幕优选模式时是正常展开
![Screenshot_20241025_180223](https://github.com/user-attachments/assets/e0efe074-928b-40a2-a940-35d7916c231f)
收起展开时就关闭弹幕优选
![Screenshot_20241025_180220](https://github.com/user-attachments/assets/e368eeb5-68be-4c0f-ba71-e49099c5cdd1)

### 功能逻辑

将视频播放器里展开收起弹幕优选按钮与全局设置里的弹幕优选按钮开关绑定

**Comment by zjns** [comment]
非常麻烦
