### ISSUE TITLE
[Feature] 有没有办法统一动态里文字动态的排版？

### ISSUE THREAD

**Issue by doveyo** [zjns/BiliRoamingX-integrations#550]
### 原因

经常看文字动态，每次点全文的时候这文字排版都变动了，点进去还得找一会位置！
![fbfcf0b48831fa228e1e898c99075296](https://github.com/user-attachments/assets/b218e8ec-02b9-4fd5-aa10-08afe4cac247)
![959765bee66fee5ae23badacc2684383](https://github.com/user-attachments/assets/ea7ff2fe-5584-42e4-a1ff-9f7fe01ff014)

### 功能简述

有没有办法统一动态里文字动态的排版？

### 功能逻辑

统一动态里文字动态的排版？已经反馈过B站官方，也不知道有没有用！！！

**Comment by doveyo** [comment]
我从官版的8.9.0版本往下测试，到8.6.0版本才不会有这种反人类的排版！

**Comment by zjns** [comment]
字体大小不一样，目前可以变相解决，搜索 文本折叠控制
