### ISSUE TITLE
查看已被拉黑up主的直播

### ISSUE THREAD

**Issue by MegumiN152** [zjns/BiliRoamingX-integrations#558]
目前高版本app无法看已被拉黑up主的直播，大佬能否加个功能解开这个限制呢

**Comment by zjns** [comment]
开启调试模式，进入被拉黑直播间，上传日志至此

**Comment by MegumiN152** [comment]
![log_哔哩哔哩HD.zip](https://github.com/user-attachments/files/17833694/log_.HD.zip)

**Comment by zjns** [comment]
> ![log_哔哩哔哩HD.zip](https://github.com/user-attachments/files/17833694/log_.HD.zip)

日至没上传成功

**Comment by Miscede** [comment]
能不能增加过滤竖屏模式下，广告浮窗的功能模块

**Comment by Rude56** [comment]
希望漫游屏蔽能长按编辑关键词，现在只能添加一整个标题，要到设置里改，很麻烦![S41204-18514985_tv.danmaku.bili.png](https://github.com/user-attachments/assets/0b04f067-a792-4d63-b117-cf36ffd7332c)

**Comment by hyh155520** [comment]
为什么高版本直到1.23.3，没有1.25吗？
