### ISSUE TITLE
feat: 能不能弄个CI构建的频道，更新周期有点长，想用预览版

### ISSUE THREAD

**Issue by yihao0628** [zjns/BiliRoamingX-integrations#56]
### 原因

提出的问题已经被修复但新版本发布周期长

### 功能简述

用action自动构建新版本bilibili后推送到CI构建频道

### 功能逻辑

如上

### 实现参考

QAuxilary的CI构件频道
https://t.me/QAuxiliary_CI
QAuxilary的github actions
https://t.me/QAuxiliary_CI

**Comment by zjns** [comment]
CI构建意义不大，如果实在想提前使用最新版本，可参考revanced官方打包指南自己打包。
