### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Yan546** [zjns/BiliRoamingX-integrations#561]
视频评论区工房链接点击不会弹出工房商品详情
粉版8.21.0 X1.25.0，上版就有这个问题了

https://github.com/user-attachments/assets/d70d7e61-8b96-4598-ba93-c97fbecc5318

**Comment by zjns** [comment]
视频bv号呢

**Comment by Yan546** [comment]
> 视频bv号呢

BV1iJsve5Eir

**Comment by Yan546** [comment]
[BiliRoamingX_Pink_backup_20241120115337.zip](https://github.com/user-attachments/files/17824630/BiliRoamingX_Pink_backup_20241120115337.zip)
漫游设置

**Comment by zjns** [comment]
临时办法：关闭 禁止采集隐私信息
