### ISSUE TITLE
[Feature] 希望为非大会员用户开放一部分功能

### ISSUE THREAD

**Issue by LKWeng** [zjns/BiliRoamingX-integrations#567]
### 原因

您好，我使用B站主要为了听视频与直播，不会在会员购购物、不会看番剧也不会上传视频。现在B站强推的功能对我而言太过繁杂，大会员功能对我也没有价值。所以希望您能为非大会员用户解禁一部分与大会员特权无关的功能。

### 功能简述

希望能为非大会员用户解禁一部分与大会员特权无关的功能。比如
1.UI屏蔽功能，隐藏底部功能栏、"我的"页面的无用功能等
![IMG_20241123_092127](https://github.com/user-attachments/assets/60b6ee64-22d0-49c4-8950-38445f9d9575)

2.禁止竖屏功能

3.推荐过滤，过滤一部分特定视频

无论结果如何，感谢您的付出与分享

### 功能逻辑

感谢

**Comment by zjns** [comment]
麻烦

**Comment by LKWeng** [comment]
我去充大会员吧，感谢
