### ISSUE TITLE
[BUG] 通过YouTube绑定的视频不显示标记的片段

### ISSUE THREAD

**Issue by datou1996** [zjns/BiliRoamingX-integrations#568]
### 系统版本

RedMagicOS 9.5.19MR1

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.21.0

### 问题描述

在网页端通过绑定YouTube搬运视频链接方式标记的片段在app端不显示。

### 复现步骤

打开对应视频，无投票按钮，进度条无片段。

### 日志

[log_哔哩哔哩.zip](https://github.com/user-attachments/files/17878278/log_.zip)

### 截图或录屏

![image](https://github.com/user-attachments/assets/7fb28678-a91d-4f5d-8330-fde1e5742128)
![Screenshot_20241123_115231](https://github.com/user-attachments/assets/0bd5d68f-c02d-4948-a9e6-65f8fa7e4248)
![Screenshot_20241123_115256](https://github.com/user-attachments/assets/c97a9637-eca9-4626-b879-63420eeaa88e)

### 补充信息

b站视频：https://www.bilibili.com/video/BV1vz4y1q7hf
对应YouTube视频：https://youtu.be/QrYIOjs7K8E

**Comment by datou1996** [comment]
> ### 系统版本
> RedMagicOS 9.5.19MR1
> 
> ### Android 版本
> 14
> 
> ### 哔哩哔哩版本
> 粉版（普通版）
> 
> ### 哔哩哔哩版本号
> 8.21.0
> 
> ### 问题描述
> 在网页端通过绑定YouTube搬运视频链接方式标记的片段在app端不显示。
> 
> ### 复现步骤
> 打开对应视频，无投票按钮，进度条无片段。
> 
> ### 日志
> [log_哔哩哔哩.zip](https://github.com/user-attachments/files/17878278/log_.zip)
> 
> ### 截图或录屏
> _No response_
> 
> ### 解决办法
> _No response_
> 
> ### 补充信息
> b站视频：https://www.bilibili.com/video/BV1vz4y1q7hf
对应YouTube视频：https://youtu.be/QrYIOjs7K8E

**Comment by zjns** [comment]
网页插件及后端api问题，等他们更新
