### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by sunset191** [zjns/BiliRoamingX-integrations#569]
### 原因

您好，很高兴向您发来信息，您的软件很棒，几乎没有任何缺点，无论是使用体验还是功能的全面性，都无可挑剔，特别是无广告性真的特别棒，一直有在使用，很感谢您的贡献，作为用户也在好好遵守您设定的规则，最近一段时间被禁用了，我看了原因，有些看不懂，希望您能可以给我解禁，再次感谢您的贡献。我的UID:19545967

### 功能简述

感谢您的贡献

### 功能逻辑

感谢您的贡献

### 实现参考

感谢您的贡献

**Comment by wyi6** [comment]
头一段时间，有人在国内平台大规模宣传
解析服务器把所有人都给拉黑了

解决办法:上频道下载最新版本

在漫游设置－关于里面可以找到

**Comment by wyi6** [comment]
同时也建议你到https://black.qimo.ink/
检查一下自己有没有被加入黑名单
如果有 请删除自己的违规评论并申诉
