### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by anchengc123** [zjns/BiliRoamingX-integrations#573]
### 系统版本

hyperos1

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.23.0

### 问题描述

哔哩漫游网络连接错误，upos测速失败，无法检查更新

### 复现步骤

稳定复现

### 日志

无

**Comment by anchengc123** [comment]
日志
[log_哔哩哔哩.zip](https://github.com/user-attachments/files/17967519/log_.zip)

**Comment by anchengc123** [comment]
![Screenshot_2024-12-01-09-05-29-255_tv danmaku bili](https://github.com/user-attachments/assets/f773854d-702e-4731-aead-1ae662ba71d8)
![Screenshot_2024-12-01-09-05-34-327_tv danmaku bili](https://github.com/user-attachments/assets/92c23a9a-a92f-4e65-b419-84a54945afae)
![Screenshot_2024-12-01-09-05-40-330_tv danmaku bili](https://github.com/user-attachments/assets/71af5567-64ba-48ab-ac51-171f132ac6ed)
![Screenshot_2024-12-01-09-05-46-575_tv danmaku bili](https://github.com/user-attachments/assets/bd7d8d9e-554d-4ada-976f-1d4e1e40f60a)

**Comment by anchengc123** [comment]
![Screenshot_2024-12-01-09-05-29-255_tv danmaku bili](https://github.com/user-attachments/assets/f5264155-dace-46c9-a974-d5da6b2d0c7e)
![Screenshot_2024-12-01-09-05-34-327_tv danmaku bili](https://github.com/user-attachments/assets/7eaed601-6494-4678-a758-af6eb4432355)
![IMG_20241201_090729](https://github.com/user-attachments/assets/2833e0bd-5797-427a-aa51-ab68dbb3d80f)
![Screenshot_2024-12-01-09-05-46-575_tv danmaku bili](https://github.com/user-attachments/assets/ea1a7c22-dc3f-4707-92e2-6c0dea95d453)

**Comment by zjns** [comment]
你填的解析服务器不可用

**Comment by anchengc123** [comment]
> 你填的解析服务器不可用

我已经在网页端确保解析服务器可用，但手机端依旧不行，我尝试过更换手机，仍然网络错误
