### ISSUE TITLE
[BUG] 账号被封禁，此前没有接触或了解过哔哩漫游

### ISSUE THREAD

**Issue by xiaoniao427** [zjns/BiliRoamingX-integrations#574]
### 系统版本

xiaomi hyperos1.0.19.0

### Android 版本

14

### 哔哩哔哩版本

Play 版（国际版）

### 哔哩哔哩版本号

3.19.2

### 问题描述

哔哩漫游提示被封禁，纸飞机查询没有查询到封禁记录
具体信息如图
![Uploading Screenshot_2024-12-01-20-49-45-614_org.telegram.messenger.jpg…]()
![Uploading Screenshot_2024-12-01-20-27-28-706_com.bilibili.app.in.jpg…]()

### 复现步骤

无

### 日志

无

### 截图或录屏

![Screenshot_2024-12-01-20-49-45-614_org telegram messenger](https://github.com/user-attachments/assets/e64d4ade-b705-47f4-a317-6af0ac658fca)
![Screenshot_2024-12-01-20-27-28-706_com bilibili app in](https://github.com/user-attachments/assets/a47a469c-0057-4532-9791-9ca71bbdb5fd)

**Comment by zjns** [comment]
用新版

**Comment by xiaoniao427** [comment]
感谢
