### ISSUE TITLE
[BUG] 空降助手设置不见了

### ISSUE THREAD

**Issue by emptylight370** [zjns/BiliRoamingX-integrations#575]
### 系统版本

ColorOS 14

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.23.0

### 问题描述

更新1.25.1之后，在设置里看不见空降助手的设置，但是设置沿用之前已经设置好的设置项

### 复现步骤

1. 更新1.25.1
2. 打开哔哩漫游X设置
3. 翻看所有设置

### 日志

file_hidden[](https://github.com/user-attachments/files/17979813/log_.zip)

**Comment by QwYoufu** [comment]
去看群组哇

**Comment by emptylight370** [comment]
> 去看群组哇

正被tg挡在门外，进不去了
