### ISSUE TITLE
第一次使用，登陆就说我违规被封禁

### ISSUE THREAD

**Issue by fllesser** [zjns/BiliRoamingX-integrations#576]
### 系统版本

鸿蒙 4.2

### Android 版本

10

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.21.0

### 问题描述

第一次使用，登陆任何一个账号都说我违反规定被封禁，去tg查也没有我的uid，不懂

### 复现步骤

....

### 日志

...

### 截图或录屏

...

**Comment by zjns** [comment]
用新版

**Comment by fllesser** [comment]
> 用新版

新版不知道在哪下，刚看到这个 repo 删了，能指个路吗
