### ISSUE TITLE
[Feature] 手动指定并劫持视频与直播CDN地址 或ipv6-only功能

### ISSUE THREAD

**Issue by DebussyS** [zjns/BiliRoamingX-integrations#577]
### 原因

1. 部分CDN没有ipv6解析
2. 直播部分源是纯IPv4播放地址，个人网络环境不希望ipv4有大流量

### 功能简述

禁用纯IP地址的直播源，可以指定CDN地址

### 功能逻辑

填写完整CDN地址，不限于upos

### 实现参考

https://greasyfork.org/en/scripts/473962-custom-cdn-url

**Comment by DebussyS** [comment]
注意到integrations/app/src/main/java/app/revanced/bilibili/utils/UposReplacer.kt 已有cdn判定机制，希望在此基础上可以允许禁用或手动选择优先的cdn

**Comment by zjns** [comment]
有何意义，直播能正常看不就行了

**Comment by DebussyS** [comment]
> 有何意义，直播能正常看不就行了

我的网络使用ipv6是不计费的。
我如果使用代理软件指定ipv6-only，那b站的直播源是没有fallback切换机制的，直播可以选择的4个直播源可能没有一个支持ipv6（仅限移动端，网页端有切换cdn机制）
