### ISSUE TITLE
[Feature] 播放页简介长按的便捷复制功能

### ISSUE THREAD

**Issue by LucasXue** [zjns/BiliRoamingX-integrations#579]
### 原因

原本使用的漫游版本，有播放页简介长按的便捷复制功能，长按简介会弹出额外的文本框，可以长按选择复制。使用的新版本包体后，现在找不到了

### 功能简述

原本使用的漫游版本，有播放页简介长按的便捷复制功能，长按简介会弹出额外的文本框，可以长按选择复制。使用的新版本包体后，现在找不到了

### 功能逻辑

原本使用的漫游版本，有播放页简介长按的便捷复制功能，长按简介会弹出额外的文本框，可以长按选择复制。使用的新版本包体后，现在找不到了

### 实现参考

原本使用的漫游版本，有播放页简介长按的便捷复制功能，长按简介会弹出额外的文本框，可以长按选择复制。使用的新版本包体后，现在找不到了

**Comment by MiKoto-Railgun** [comment]
不是有的吗？漫游X设置杂项里的复制一栏，两个全开不就好了
