### ISSUE TITLE
bug: 在“我的页面”更改“需要展示的项目”无效

### ISSUE THREAD

**Issue by jsc06** [zjns/BiliRoamingX-integrations#58]
### 系统版本

Origin OS 1.0 for IQOO

### Android 版本

11

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.46.0

### 问题描述

在“我的页面”更改“需要展示的项目”无效，重新打开我的页面后仍旧只有那五个选项
![Screenshot_20231103_013510](https://github.com/zjns/BiliRoamingX-integrations/assets/99361974/19135d53-4002-4990-b9e7-9ad603bc7128)
![Screenshot_20231103_013438](https://github.com/zjns/BiliRoamingX-integrations/assets/99361974/5f2bffa2-0c19-4538-9b5c-303225f1d2fe)
![Screenshot_20231103_013434](https://github.com/zjns/BiliRoamingX-integrations/assets/99361974/81108fc9-d1ef-4979-b972-f6b2fcd0e0a3)

### 复现步骤

打开设置，点击哔哩漫游X，点击我的页面，点击需要展示的项目，进行勾选后重启应用多次，但在我的页面仍然只有如图的五个选项
![Screenshot_20231103_013510](https://github.com/zjns/BiliRoamingX-integrations/assets/99361974/bc442078-0e75-4336-8601-d6843e7cef93)

### 日志

[log.txt](https://github.com/zjns/BiliRoamingX-integrations/files/13242886/log.txt)

### 截图或录屏

https://github.com/zjns/BiliRoamingX-integrations/assets/99361974/12ca49ba-cb28-4dbf-be03-7e5a514e8aea

**Comment by Myth1848** [comment]
需要勾选对应的标题项目

**Comment by jsc06** [comment]
> 需要勾选对应的标题项目

看视频已经勾选了，但是除了初始五项以外，不会显示出我勾选的其他项目
