### ISSUE TITLE
[Feature] 希望添加完全的简介复制功能

### ISSUE THREAD

**Issue by MiKoto-Railgun** [zjns/BiliRoamingX-integrations#581]
### 原因

有时候标题里自带了一些内容我想复制，但只能长按简介后弹出完整内容复制弹窗后进行复制，但就是吧有些视频要么是没有简介的，要么是只有“-”这个字符，像这种情况就没法长按复制了

### 功能简述

所以我希望可以给标题也单独添加长按自由复制功能

### 功能逻辑

希望标题长按后，可以弹出简介长按后弹出的完整内容复制弹窗

### 实现参考

为标题添加长按事件，并绑定到简介长按后弹出的完整内容复制弹窗的事件上，应该只要添加绑定事件就好了

**Comment by Tully44** [comment]
没有简介的长按bv号也可以自由复制

**Comment by MiKoto-Railgun** [comment]
> 没有简介的长按bv号也可以自由复制

谢了哥们，这还是第一次知道
