### ISSUE TITLE
[BUG] 安装调整设置后未进行其他行为被封禁且本UID未出现在封禁电报群

### ISSUE THREAD

**Issue by moshang-233** [zjns/BiliRoamingX-integrations#585]
### 系统版本

xiaomi HyperOS2.0.5.0.VNMCNXM

### Android 版本

15

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.14.0

### 问题描述

下载完毕后，安装并进行了个人设置，重启后成功使用一小段时间，然后弹出提示框显示被封禁至2077年，期间没有发布任何评论，没有使用任何解析服务器。根据提示进入电报群查看，搜索并未出现本人UID，加入解封群申请至今没有通过，本人UID:32274245，望解决，感谢。

### 复现步骤

同问题描述

### 日志

[log_哔哩哔哩.zip](https://github.com/user-attachments/files/18205288/log_.zip)

**Comment by zjns** [comment]
用最新版本
