### ISSUE TITLE
bug: <设置入口消失>

### ISSUE THREAD

**Issue by hsichien** [zjns/BiliRoamingX-integrations#6]
### Type

Cosmetic

### Bug description

一段时间前精简过"我的"页面，今天发现设置入口消失了，预期情况下设置按钮会在"有奖活动"右侧

版本: 7.39.0

### Steps to reproduce

打开哔哩哔哩-点击"我的"

### Relevant log output

```shell
none
```

### Screenshots or videos

![Screenshot_2023-07-27-17-07-45-22_149003a2d400f6adb210d7e357a3a646](https://github.com/zjns/BiliRoamingX-integrations/assets/78013146/2e8a8dc9-acb1-4f84-82ef-5a63e14689a3)

**Comment by hsichien** [comment]
https://t.wss.ink/f/bsl5w93tq77
附上哔哩漫游X设置

**Comment by zjns** [comment]
不要取消勾选 “更多服务” 标题项目
