### ISSUE TITLE
我的页面图标显示有问题

### ISSUE THREAD

**Issue by Sooonar** [zjns/BiliRoamingX-integrations#60]
### 系统版本

origin os3

### Android 版本

13

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.53.0

### 问题描述

1、在字体放大后，进入我的页面，下拉刷新后设置图标会忽大忽小。
2、页面样式调整为列表后“稍后在看”没有了。（ps这个不是很重要）

### 复现步骤

1、在字体放大后。
2、进入我的页面（侧边栏也会出现）。
3、下拉刷新后“设置”图标会忽大忽小。

### 日志

sorry啊，大佬我折腾了一中午，没找到那个调试文件。(ಥ﹏ಥ)

### 截图或录屏

Uploading Screenrecording_20231103_120059.mp4…

### 解决办法

最后一个版本了，麻烦大佬改一下，谢谢你嘞
(*´ω｀*)

**Comment by zjns** [comment]
稍后再看在设置里面重新勾选就行，图标问题不重要，请自适应忽略，不要太过强迫症。
