### ISSUE TITLE
bug: 每天前几次打开还是有启动广告

### ISSUE THREAD

**Issue by recycle007** [zjns/BiliRoamingX-integrations#62]
### 系统版本

氢os

### Android 版本

10

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.53.0

### 问题描述

设置里已经打开净化开屏广告选项，但每天前几次打开还是有启动广告，清除缓存还是不行

### 复现步骤

打开app

### 日志

[log.txt](https://github.com/zjns/BiliRoamingX-integrations/files/13260214/log.txt)

### 截图或录屏

![Screenshot_20231106-002831](https://github.com/zjns/BiliRoamingX-integrations/assets/82096497/2d3eb762-b105-4d52-9692-63c0a7a15e34)
![Screenshot_20231106-002824](https://github.com/zjns/BiliRoamingX-integrations/assets/82096497/cd68984b-2dfd-489d-8ea9-a1779b8e1303)

**Comment by zjns** [comment]
咋自己关了，好了？
