### ISSUE TITLE
 qqvx不能分享

### ISSUE THREAD

**Issue by chaonaimoluoganbeng** [zjns/BiliRoamingX-integrations#66]
### 系统版本

MIUI14.0.13

### Android 版本

13

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.56.0

### 问题描述

分享显示非官方应用😭

### 复现步骤

.

### 日志

.

**Comment by lyl13145200** [comment]
不能分享加一，错误代码25201
