### ISSUE TITLE
bug: 字幕不显示

### ISSUE THREAD

**Issue by TonyYu123** [zjns/BiliRoamingX-integrations#68]
### 系统版本

MIUI14

### Android 版本

12

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.56.0

### 问题描述

泰区cc字幕不显示

### 复现步骤

1.打开泰区番剧
2.打开字幕

### 日志

[log(1).txt](https://github.com/zjns/BiliRoamingX-integrations/files/13533405/log.1.txt)

### 截图或录屏

![486879e5cd191e1f3f13b635086c3d6](https://github.com/zjns/BiliRoamingX-integrations/assets/68726306/125730af-630e-4bb1-b014-ec798a471f96)

### 补充信息

我推的孩子

**Comment by TonyYu123** [comment]
泰区所有番剧都有这个bug

**Comment by TonyYu123** [comment]
但是在school days 第十二集里的中文字幕是可用的

**Comment by NaNaChi-Sama** [comment]
这bug好像不是不显示字幕，而是初次加载番剧的时候没加载字幕，换一集之后字幕就能正常加载，然后再换回刚才的一集也正常了。这bug在上个漫游X的版本就没有，原版哔哩漫游在高版本也有这个bug，具体哪个版本开始我就没挨个试了

**Comment by NaNaChi-Sama** [comment]
补充一句，高版本指的是高版本哔哩哔哩

**Comment by TonyYu123** [comment]
感谢
