### ISSUE TITLE
bug: 开启自动领取卡券之后每次启动app都会提示一次卡券领取成功

### ISSUE THREAD

**Issue by Misaka123** [zjns/BiliRoamingX-integrations#73]
### 系统版本

MIUI 14

### Android 版本

Android 13

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.56.0

### 问题描述

开启自动领取卡券之后每次启动app都会提示一次卡券领取成功

### 复现步骤

1开启自动领取卡券
2重启app

### 日志

[old_log.txt](https://github.com/zjns/BiliRoamingX-integrations/files/13656012/old_log.txt)
[log.txt](https://github.com/zjns/BiliRoamingX-integrations/files/13656013/log.txt)

### 截图或录屏

![Screenshot_2023-12-13-12-19-10-295_tv danmaku bili](https://github.com/zjns/BiliRoamingX-integrations/assets/24843118/716faa48-f25b-4337-a1b2-691565b60091)

**Comment by zjns** [comment]
https://github.com/zjns/BiliRoamingX-integrations/commit/7e83dce10224aef9a0f67fc29e186600919568a0
