### ISSUE TITLE
去除开屏启动推广有时会失效

### ISSUE THREAD

**Issue by M-HLSLY** [zjns/BiliRoamingX-integrations#76]
### 系统版本

RealmeUI4.0

### Android 版本

13

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.56.0

### 问题描述

在“净化开屏界面”选项为开启的情况下有时仍会有开屏广告

### 复现步骤

1.打开选项开关
2.反复重启或杀掉进程后重启

### 日志

[log.txt](https://github.com/zjns/BiliRoamingX-integrations/files/13693222/log.txt)

### 截图或录屏

![Screenshot_2023-12-17-00-44-23-55_149003a2d400f6adb210d7e357a3a646](https://github.com/zjns/BiliRoamingX-integrations/assets/102822186/b114c7f4-ddea-44e3-866a-f7bb12669cc2)
![Screenshot_2023-12-17-00-44-12-35_149003a2d400f6adb210d7e357a3a646](https://github.com/zjns/BiliRoamingX-integrations/assets/102822186/c21d704f-0b5d-486b-9f03-fdb2cac51e9b)

**Comment by zjns** [comment]
开启后用了几天后都还会时不时出现广告？

**Comment by zjns** [comment]
用tg群里的最新版本试试
