### ISSUE TITLE
feat: Hardware Decoding

### ISSUE THREAD

**Issue by Azusa-mikan** [zjns/BiliRoamingX-integrations#77]
### 原因

某些情况下，死妈哔哩哔哩并不会去硬解视频

### 功能简述

增加强制使用硬解功能

### 功能逻辑

在播放器选项卡添加“强制硬解视频”选项即可，谢谢你！

**Comment by zjns** [comment]
B 站现在就是优先硬解呀

**Comment by zjns** [comment]
4afbab3e572c2ce3025a6ff21e8c1d2bc4310aed

**Comment by Azusa-mikan** [comment]
> B 站现在就是优先硬解呀

高通没问题，可是mtk用户很惨
