### ISSUE TITLE
bug: 泰区播放显示资源不存在

### ISSUE THREAD

**Issue by boysimple** [zjns/BiliRoamingX-integrations#79]
### 系统版本

flyme 10

### Android 版本

13

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

最新

### 问题描述

泰区搜索正常 点进去后显示资源存在

### 复现步骤

搜索任意一部泰区番剧 点击播放

### 日志

--------- beginning of main
12-22 08:00:37.643 23952 23952 E tv.danmaku.bili: No package ID 3c found for ID 0x3c83bfeb.
12-22 08:00:37.659 23952 23952 E tv.danmaku.bili: No package ID 3c found for ID 0x3c83bfeb.
12-22 08:00:37.725 23952 23952 E tv.danmaku.bili: No package ID 3c found for ID 0x3c83bfeb.
12-22 08:00:37.727 23952 23952 E tv.danmaku.bili: No package ID 38 found for ID 0x3849d323.
12-22 08:00:37.727 23952 23952 E tv.danmaku.bili: No package ID 31 found for ID 0x312ffaaf.
12-22 08:00:37.746 23952 23952 E SVGAImageView: stopAnimation:animator = null }
12-22 08:00:37.838 23952 23952 E tv.danmaku.bili: No package ID 38 found for ID 0x3849d323.
12-22 08:00:37.838 23952 23952 E tv.danmaku.bili: No package ID 31 found for ID 0x312ffaaf.
12-22 08:00:37.839 23952 23952 E tv.danmaku.bili: No package ID 3c found for ID 0x3c83bfeb.
12-22 08:00:37.873 23952 23952 I Choreographer: Skipped 6 frames!  The application may be doing too much work on its main thread.
12-22 08:00:38.409 23952 2

**Comment by zjns** [comment]
最新是什么版本？？7.60.0已经修复。
