### ISSUE TITLE
bug: 从未观看过的视频也会自动跳转上次进度

### ISSUE THREAD

**Issue by 2607627233** [zjns/BiliRoamingX-integrations#8]
### 系统版本

color os

### Android 版本

13

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.39.0

### 问题描述

rt，打开从未观看过的视频 ，有概率触发自动跳转进度

### 复现步骤

打开视频

### 日志

触发概率很低 ，在打开调试模式后还没有遇到

**Comment by zjns** [comment]
看描述有可能是官方的bug。
