### ISSUE TITLE
泰区字幕无法加载

### ISSUE THREAD

**Issue by makoto-1** [zjns/BiliRoamingX-integrations#81]
### 系统版本

ColorOS 13.1

### Android 版本

13

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.60.0

### 问题描述

打开泰区视频后，视频播放正常，但不出现字幕

### 复现步骤

1.搜索某部番剧（如电锯人）
2.在泰区中点开观看
3.之后即可发现无法加载字幕

### 日志

--------- beginning of main
12-22 23:43:35.841 18779 25539 D revanced: Settings: Loaded setting 'BLOCK_TOP_ACTIVITY' with value false
12-22 23:43:35.841 18779 25539 D revanced: Settings: Loaded setting 'BLOCK_RECOMMEND_GUIDANCE' with value false
12-22 23:43:35.841 18779 25539 D revanced: Settings: Loaded setting 'BLOCK_POPULAR_TOP_ENTRANCE' with value false
12-22 23:43:35.841 18779 25539 D revanced: Settings: Loaded setting 'BLOCK_POPULAR_TOPIC_LIST' with value false
12-22 23:43:35.841 18779 25539 D revanced: Settings: Loaded setting 'BLOCK_POPULAR_RCMD_UP' with value false
12-22 23:43:35.841 18779 25539 D revanced: Settings: Loaded setting 'DYNAMIC_PREFER_VIDEO_TAB' with value false
12-22 23:43:35.841 18779 25539 D revanced: Settings: Loaded setting 'DYNAMIC_PURIFY_CITY' with value false
12-22 23:43:35.841 18779 25539 D revanced: Settings: Loaded setting 'DYNAMIC_PURIFY_CAMPUS' with value false
12-22 23:43:35.841 18779 25539 D revanced: Settings: Loaded setting 'DYNAMIC_RM_TOPIC_OF_ALL' with value false
12-22 23:43:35.841 18779 25539 D revanced: Settings: Loaded setting 'DYNAMIC_RM_UP_OF_ALL' with value false
12-22 23:43:35.841 18779 25539 D revanced: Settings: Loaded setting 'DYNAMIC_RM_UP_OF_VIDEO' with value false
12-22 23:43:35.841 18779 25539 D revanced: Settings: Loaded setting 'DYNAMIC_FILTER_APPLY_TO_VIDEO' with value false
12-22 23:43:35.841 18779 25539 D revanced: Settings: Loaded setting 'DYNAMIC_RM_BLOCKED' with value true
12-22 23:43:35.841 18779 25539 D revanced: Settings: Loaded setting 'DYNAMIC_RM_AD_LINK' with value true
12-22 23:43:35.841 18779 25539 D revanced: Settings: Loaded setting 'DYNAMIC_RM_UP_RESERVATION' with value true
12-22 23:43:35.841 18779 25539 D revanced: Settings: Loaded setting 'DYNAMIC_PURIFY_TYPE' with value [24, 14, 4, 15, 18]
12-22 23:43:35.841 18779 25539 D revanced: Settings: Loaded setting 'DYNAMIC_PURIFY_CONTENT' with value []
12-22 23:43:35.841 18779 25539 D revanced: Settings: Loaded setting 'DYNAMIC_PURIFY_CONTENT_REGEX_MODE' with value false
12-22 23:43:35.841 18779 25539 D revanced: Settings: Loaded setting 'DYNAMIC_PURIFY_UP' with value []
12-22 23:43:35.841 18779 25539 D revanced: Settings: Loaded setting 'DYNAMIC_PURIFY_UID' with value []
12-22 23:43:35.841 18779 25539 D revanced: Settings: Loaded setting 'DYNAMIC_PURIFY_TOPIC' with value []
12-22 23:43:35.841 18779 25539 D revanced: Settings: Loaded setting 'DRAWER_STYLE' with value 0
12-22 23:43:35.841 18779 25539 D revanced: Settings: Loaded setting 'PURIFY_DRAWER_RED_DOT' with value false
12-22 23:43:35.841 18779 25539 D revanced: Settings: Loaded setting 'REMOVE_VIP_SECTION' with value false
12-22 23:43:35.841 18779 25539 D revanced: Settings: Loaded setting 'SHOWING_DRAWER_ITEMS' with value [190, 191, 390, 172, 392, 有奖发布, 395, 创作中心, 531, 379, 874, 875, 877, 2908, 811, 游戏中心, 878, 2829, 879, 推荐服务, 517, 914, 查看更多, 383, 384, 880, 386, 更多服务, 388, 543, 1388, 624, 923, 967, 989]
12-22 23:43:35.842 18779 25539 D revanced: Settings: Loaded setting 'SWITCH_DARK_DIALOG' with value false
12-22 23:43:35.842 18779 25539 D revanced: Settings: Loaded setting 'FORBID_SWITCH_LIVE_ROOM' with value false
12-22 23:43:35.842 18779 25539 D revanced: Settings: Loaded setting 'DISABLE_LIVE_ROOM_DOUBLE_CLICK' with value false
12-22 23:43:35.842 18779 25539 D revanced: Settings: Loaded setting 'PURIFY_LIVE_POPUPS' with value []
12-22 23:43:35.842 18779 25539 D revanced: Settings: Loaded setting 'AUTO_LIKE' with value false
12-22 23:43:35.842 18779 25539 D revanced: Settings: Loaded setting 'SAVE_COMMENT_IMAGE' with value true
12-22 23:43:35.842 18779 25539 D revanced: Settings: Loaded setting 'UNLOCK_PLAY_LIMIT' with value true
12-22 23:43:35.842 18779 25539 D revanced: Settings: Loaded setting 'REPLACE_STORY_VIDEO' with value true
12-22 23:43:35.842 18779 25539 D revanced: Settings: Loaded setting 'DISABLE_STORY_FULL' with value true
12-22 23:43:35.842 18779 25539 D revanced: Settings: Loaded setting 'REMOVE_CMD_DMS' with value true
12-22 23:43:35.842 18779 25539 D revanced: Settings: Loaded setting 'BLOCK_WORD_SEARCH' with value false
12-22 23:43:35.842 18779 25539 D revanced: Settings: Loaded setting 'BLOCK_COMMENT_GUIDE' with value false
12-22 23:43:35.842 18779 25539 D revanced: Settings: Loaded setting 'BLOCK_VIDEO_COMMENT' with value false
12-22 23:43:35.842 18779 25539 D revanced: Settings: Loaded setting 'BLOCK_UP_RCMD_ADS' with value true
12-22 23:43:35.842 18779 25539 D revanced: Settings: Loaded setting 'BLOCK_BANGUMI_PAGE_ADS' with value true
12-22 23:43:35.842 18779 25539 D revanced: Settings: Loaded setting 'REMOVE_RELATE_PROMOTE' with value true
12-22 23:43:35.842 18779 25539 D revanced: Settings: Loaded setting 'REMOVE_RELATE_ONLY_AV' with value false
12-22 23:43:35.842 18779 25539 D revanced: Settings: Loaded setting 'REMOVE_RELATE_NOTHING' with value false
12-22 23:43:35.842 18779 25539 D revanced: Settings: Loaded setting 'DISABLE_AUTO_SELECT' with value false
12-22 23:43:35.842 18779 25539 D revanced: Se

### 截图或录屏

![IMG_20231222_235723](https://github.com/zjns/BiliRoamingX-integrations/assets/150347006/f922d95b-7669-4049-8cb9-6b10bca38b9a)

![IMG_20231222_235808](https://github.com/zjns/BiliRoamingX-integrations/assets/150347006/f98c4f6e-1682-4ece-8561-12acb3218b3c)

### 解决办法

之前的版本（7.53.0)字幕加载正常，更新后无法加载

### 补充信息

电锯人、进击的巨人、我推的孩子等番剧字幕无法加载，可能泰区的所有视频的字幕都看不了

**Comment by zjns** [comment]
已知问题，临时解决办法：切集后正常。

**Comment by makoto-1** [comment]
临时解决方法（切集）已尝试，但字幕依旧无法加载
