### ISSUE TITLE
强制显示原生音乐通知失效

### ISSUE THREAD

**Issue by Enmmma** [zjns/BiliRoamingX-integrations#87]
### 系统版本

coloros14

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.63

### 问题描述

开启强制原生之后，通知不显示，关闭设置，可以正常显示通知

### 复现步骤

打开设置内强制原生选项

### 日志

[log.txt](https://github.com/zjns/BiliRoamingX-integrations/files/13920610/log.txt)

### 补充信息

任何视频，都不显示通知

**Comment by zjns** [comment]
ColorOS的问题

**Comment by zjns** [comment]
> 那有什么其他办法可以解决吗，比如这类型的magisk模块？

不知道，系统魔改了音乐通知，不知道是不是加了白名单控制，如果是，那Xposed写模块应该能解决，用一加12的时候就发现这问题了。
