### ISSUE TITLE
关于我的设置无法正常打开

### ISSUE THREAD

**Issue by chen135679** [zjns/BiliRoamingX-integrations#88]
### 系统版本

MIUI14

### Android 版本

13

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

1.16

### 问题描述

无法显示设置

### 复现步骤

首页-我的-设置被隐藏

### 日志

[Uploading log.txt…]()

### 截图或录屏

![Screenshot_2024-01-15-16-04-40-382_tv danmaku bili](https://github.com/zjns/BiliRoamingX-integrations/assets/115053809/7db801f6-46c0-4d79-a6f6-4d490f0b3da9)

**Comment by zjns** [comment]
我的页面净化过头了，需要展示的项目必须勾选“【标题项目】(更多服务)”

**Comment by chen135679** [comment]
谢谢
