### ISSUE TITLE
feat: 站请求通知权限

### ISSUE THREAD

**Issue by Kinda2419** [zjns/BiliRoamingX-integrations#89]
### 原因

每过一段时间，进入b站就会请求通知权限，希望能够屏蔽这个请求

### 功能简述

每过一段时间，进入b站就会请求通知权限，希望能够屏蔽这个请求

### 功能逻辑

每过一段时间，进入b站就会请求通知权限，希望能够屏蔽这个请求

**Comment by zjns** [comment]
给它通知权限
