### ISSUE TITLE
字体大小修改

### ISSUE THREAD

**Issue by Enlin1021** [zjns/BiliRoamingX-integrations#9]
### 原因

修改手机dpi后，软件显示字体大小变化，但b站未提供字体大小修改功能

### 功能简述

自定义字体大小

### 功能逻辑

滑动精确调节字体大小百分比，或者固定某些值，如字体缩放：50%   100%  150%  200%等

### 实现参考

app cloner，应用配置

**Comment by zjns** [comment]
给官方反馈。
