### ISSUE TITLE
bug: 无法切换成旧版播放器界面

### ISSUE THREAD

**Issue by mgcccc** [zjns/BiliRoamingX-integrations#90]
### 系统版本

magicos8.0

### Android 版本

安卓14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.63.0

### 问题描述

无法切换成旧版播放器界面

### 复现步骤

在哔哩漫游里切换播放器版本为旧版无效，一直是新版的样式

### 日志

找不到小长条

**Comment by zjns** [comment]
旧版播放器的进度条进度文字是加粗了的，新版偏细，先看看确认下

**Comment by mgcccc** [comment]
201338是打开旧版的，201407是打开新版的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月16日(周二) 晚上7:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zjns/BiliRoamingX-integrations] bug: 无法切换成旧版播放器界面 (Issue #90)




 
旧版播放器的进度条进度文字是加粗了的，新版偏细，先看看确认下

**Comment by zjns** [comment]
> 201338是打开旧版的，201407是打开新版的

啥意思 没听懂 我测试功能是正常的，可以强制旧版播放器

**Comment by mgcccc** [comment]
就是这两张截图一个是打开旧版播放器的截图，一个是打开新版播放器的截图，但是看上去一模一样



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月16日(周二) 晚上8:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zjns/BiliRoamingX-integrations] bug: 无法切换成旧版播放器界面 (Issue #90)




  
201338是打开旧版的，201407是打开新版的
  
啥意思 没听懂 我测试功能是正常的，可以强制旧版播放器

**Comment by zjns** [comment]
> 就是这两张截图一个是打开旧版播放器的截图，一个是打开新版播放器的截图，但是看上去一模一样

没看到你的截图

**Comment by zjns** [comment]
看进度条进度文字粗细辨别

**Comment by mgcccc** [comment]
在附件里



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月16日(周二) 晚上8:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zjns/BiliRoamingX-integrations] bug: 无法切换成旧版播放器界面 (Issue #90)




  
就是这两张截图一个是打开旧版播放器的截图，一个是打开新版播放器的截图，但是看上去一模一样
  
没看到你的截图

**Comment by mgcccc** [comment]
我横屏竖屏都截图对比了，一模一样。。。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月16日(周二) 晚上8:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zjns/BiliRoamingX-integrations] bug: 无法切换成旧版播放器界面 (Issue #90)




 
看进度条进度文字粗细辨别

**Comment by mgcccc** [comment]
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月16日(周二) 晚上8:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zjns/BiliRoamingX-integrations] bug: 无法切换成旧版播放器界面 (Issue #90)




 
并不能看到你的附件，邮箱回复附件是看不到的

**Comment by mgcccc** [comment]
![1000114332](https://github.com/zjns/BiliRoamingX-integrations/assets/117365648/512576ae-e179-4a5f-9052-9afff58a3df9)
![1000114334](https://github.com/zjns/BiliRoamingX-integrations/assets/117365648/60e76348-067c-45b4-8454-626617919c80)
这两张截图一个是旧版播放器一个是新版播放器

**Comment by zjns** [comment]
半屏播放看进度条右边的时间文字粗细比较

**Comment by mgcccc** [comment]
了解了，能不能改回更早以前的播放器



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月16日(周二) 晚上9:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zjns/BiliRoamingX-integrations] bug: 无法切换成旧版播放器界面 (Issue #90)




 
半屏播放看进度条右边的时间文字粗细比较

**Comment by zjns** [comment]
> 了解了，能不能改回更早以前的播放器
>
不能，说是新版，但更多的是接口和代码逻辑方面的变化，UI层变化不大。
