### ISSUE TITLE
bug: 强制旧版收藏逻辑无效

### ISSUE THREAD

**Issue by Spike116** [zjns/BiliRoamingX-integrations#91]
### 系统版本

coloros11

### Android 版本

11

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.63

### 问题描述

强制旧版收藏逻辑无效

### 复现步骤

gif在下边

### 日志

[log (1).txt](https://github.com/zjns/BiliRoamingX-integrations/files/13955193/log.1.txt)

### 截图或录屏

![Record_2024-01-17-03-54-46_149003a2d400f6adb210d7e357a3a646](https://github.com/zjns/BiliRoamingX-integrations/assets/104405477/52bf68ba-edd9-4b93-97bd-557447798a31)

**Comment by zjns** [comment]
日志不完整，操作到点收藏后为止

**Comment by zjns** [comment]
fixed in [28b7b42](https://github.com/zjns/BiliRoamingX-patches/commit/28b7b426cba43a090a1ade25e1ae489fbb6085ca).
