### ISSUE TITLE
会员音质破解

### ISSUE THREAD

**Issue by John1999z** [zjns/BiliRoamingX-integrations#92]
### 原因

我想尝试一下会员音质和普通音的区别。我在qq音乐感觉不到
区别。不想充钱被坑。

### 功能简述

把有h什么开头那个无损会员音质实现破解，免费使用。
![Screenshot_2024_0118_151852](https://github.com/zjns/BiliRoamingX-integrations/assets/154442352/c709ef97-66df-4386-af5d-74fd7c766a04)

### 功能逻辑

点击高画质。然后可以直接使用

**Comment by zjns** [comment]
非会员 B 站并没有提供无损音质试用，不会下发无损音质的播放链接。所以有需要请开会员！
