### ISSUE TITLE
bug: 竖屏模式无法移除充电按钮

### ISSUE THREAD

**Issue by qa9633** [zjns/BiliRoamingX-integrations#93]
### 原因

好几个版本了，一直是明明开启了去视频充电，但是重启打开视频还是有充电按钮
![Screenshot_2024-01-21-12-44-45-33_149003a2d400f6adb210d7e357a3a646](https://github.com/zjns/BiliRoamingX-integrations/assets/153371823/9a29f198-e8d2-4da4-91b7-f09119a0e62e)
![Screenshot_2024-01-21-12-44-28-43_149003a2d400f6adb210d7e357a3a646](https://github.com/zjns/BiliRoamingX-integrations/assets/153371823/fd3f3006-9a12-44ac-848c-eeaae0972271)

### 功能简述

好几个版本了，一直是明明开启了去视频充电，但是重启打开视频还是有充电按钮

### 功能逻辑

修复一下

### 实现参考

![Screenshot_2024-01-21-12-48-28-05_18fe6f119af5ae2c728d929083699df1](https://github.com/zjns/BiliRoamingX-integrations/assets/153371823/9a56ce63-3eb1-463e-b159-40a5bb7b85ca)
像play版一样没有充电按钮

**Comment by zjns** [comment]
竖屏模式忘了处理了
