### ISSUE TITLE
bug：观看视频概率闪退且无观看历史记录

### ISSUE THREAD

**Issue by M-HLSLY** [zjns/BiliRoamingX-integrations#94]
### 系统版本

RealmeUI4.0（基于ClolorOS13）

### Android 版本

13

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.63.0

### 问题描述

在观看视频时客户端有概率出现卡顿，操作无响应，重启等，重启后之前观看的视频不会留下历史记录。

### 复现步骤

暂时无法复现

### 日志

[log.txt](https://github.com/zjns/BiliRoamingX-integrations/files/14050950/log.txt)

### 解决办法

之前使用LsPatch打包的客户端也会有这种情况但比较少，不确定是否为哔哩漫游的某个功能问题。

**Comment by zjns** [comment]
该日志无效，始终打开调试模式，如果出现闪退，不要尝试重新APP，立即用文件管理器将log.txt和log_old.txt都传上来以便排查问题。

**Comment by zjns** [comment]
> 额……我的描述应该不准确，是客户端卡到重启（就像用漫游手动重启一样）。而且log_old.txt过大，无法上传
> 

过几天发个版本再看看吧，没有有效日志确实不能排查问题。

**Comment by M-HLSLY** [comment]
OK

**Comment by M-HLSLY** [comment]
> 该日志无效，始终打开调试模式，如果出现闪退，不要尝试重新APP，立即用文件管理器将log.txt和log_old.txt都传上来以便排查问题。

再次出现重启，目前概率每天一次:(
2024.1.28
![log.txt](https://github.com/zjns/BiliRoamingX-integrations/files/14082923/log.txt)

![old_log.txt](https://github.com/zjns/BiliRoamingX-integrations/files/14082924/old_log.txt)

2024.1.29
![log.txt](https://github.com/zjns/BiliRoamingX-integrations/files/14082927/log.txt)

old_log太大了，放网盘里了
https://www.123pan.com/s/AU5DVv-kSOOA.html

**Comment by zjns** [comment]
看起来貌似不是漫游X引起的，过两天我再发个包你再来打开调试模式看看，下个版本日志大小会优化，不会有这么大了
