### ISSUE TITLE
feat: 跪求大佬破解缓存大会员画质视频限制！

### ISSUE THREAD

**Issue by NewClive** [zjns/BiliRoamingX-integrations#95]
### 原因

求大佬破解一下缓存里的会员播放限制，在迁移缓存数据之后，发现以前缓存的大会员画质视频看不了了，难受。
![S40127-09464630_tv danmaku bili](https://github.com/zjns/BiliRoamingX-integrations/assets/157860167/393ddffd-e1ae-4f9f-87cb-941873768df2)

### 功能简述

希望大佬能破解播放缓存的大会员画质视频的限制。

### 功能逻辑

破解缓存大会员画质视频限制。

### 实现参考

关闭app联网权限设置后尝试播放，依旧提示限制，所以这个限制应该是本地、离线的限制。

**Comment by zjns** [comment]
没毛病，有高画质需要请开会员
