### ISSUE TITLE
长按加速禁用

### ISSUE THREAD

**Issue by Ehoumaki** [zjns/BiliRoamingX-integrations#97]
### 原因

想问下有禁用长按加速功能吗，不是很习惯。老是误触。希望能有。

### 功能简述

禁用长按加速

### 功能逻辑

或者加速里设置0就是禁用，我看好像也没作用

**Comment by zjns** [comment]
长按速度设为1不就行了！

**Comment by Ehoumaki** [comment]
😳可能是没有实际作用了，但还是会有加速提示，最主要有振动触动手感，怪怪的。
还有老大，最新版清晰度是不是失效了，不起作用。

**Comment by zjns** [comment]
> 😳可能是没有实际作用了，但还是会有加速提示，最主要有振动触动手感，怪怪的。
> 还有老大，最新版清晰度是不是失效了，不起作用。

哔哩哔哩官方关闭了会员画质试用，不管是新版播放器还是旧版播放器

**Comment by zjns** [comment]
> > 😳可能是没有实际作用了，但还是会有加速提示，最主要有振动触动手感，怪怪的。
> > 还有老大，最新版清晰度是不是失效了，不起作用。
> 
> 哔哩哔哩官方关闭了会员画质试用，不管是新版播放器还是旧版播放器

还是有少部分视频在旧版播放器中有会员画质试用

**Comment by Ehoumaki** [comment]
> > > 😳可能是没有实际作用了，但还是会有加速提示，最主要有振动触动手感，怪怪的。
> > > 还有老大，最新版清晰度是不是失效了，不起作用。
> > 
> > 
> > 哔哩哔哩官方关闭了会员画质试用，不管是新版播放器还是旧版播放器
> 
> 还是有少部分视频在旧版播放器中有会员画质试用

额 原来如此 有点恶心😭
