### ISSUE TITLE
bug: 新版播放器会员画质试用失效

### ISSUE THREAD

**Issue by maoyixuan** [zjns/BiliRoamingX-integrations#98]
### 系统版本

ColorOS 6

### Android 版本

9

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.66.0

### 问题描述

新版播放器会员画质试用失效
旧版播放器部分视频可用

### 复现步骤

用新版播放器打开一个新视频无法试用会员画质

### 日志

无

**Comment by zjns** [comment]
能否画质试用是b站接口决定的，新版播放器不能用就尝试旧版播放器，功能也有说明，如果都不行，那就说明b站关闭了所有视频的画质试用。
